### ISSUE TITLE
Invalid kubo_freq_max when fermi_energy_list is not set

### ISSUE THREAD

**Issue by greschd** [wannier-developers/wannier90#100]
When compiling with debugging flags, I get the following error when I run Wannier90: 

    Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

    Backtrace for this error:
    #0  0x7F58FEC07E08
    #1  0x7F58FEC06F90
    #2  0x7F58FE54F4AF
    #3  0x42635C in __w90_parameters_MOD_param_read at parameters.F90:1669
    #4  0x40223E in MAIN__ at wannier_prog.F90:85
    Floating point exception (core dumped)

I managed to trace the error to when ``kubo_freq_max`` is set, with a ``fermi_energy_list`` that has not been initialized before, which triggers the floating point exception. The offending line of code is this:

    if(frozen_states) then
       kubo_freq_max        = dis_froz_max-fermi_energy_list(1)+0.6667_dp

My question is this: What would the correct behaviour in this case be? Right now (without the debugging flags) it probably just creates a ``NaN``.

Compilation flags:
[make.inc.txt](https://github.com/wannier-developers/wannier90/files/779478/make.inc.txt)

**Comment by greschd** [comment]
I uploaded the input files for which I get this error here: http://z2pack.ethz.ch/54dcaf52-9c86-4cd6-b5dc-1fe2714ca45d/input.tar.bz2 
It's half a GB of data though, so it might not be worth it to download.

**Comment by giovannipizzi** [comment]
I see above in the same file that we do
```
elseif(nfermi==0) then
       ! This happens when both found_fermi_energy=.false. and                  
       ! fermi_energy_scan=.false. Functionalities that require                 
       ! specifying a Fermi level should give an error message                  
       allocate(fermi_energy_list(1),stat=ierr) ! helps streamline things       
    endif
```
Probably, we can change this to an `else` and beside allocating the Fermi energy array we also set the value to zero? It's not perfect, but anyway the default value for kubo_freq_max should be redefined properly if one uses the Kubo module, or otherwise it does not really matter.

What do you think? My gut feeling is that anyway the rest of the code is assuming to find at least one Fermi energy (e.g. below in the same file where the value is printed on output).

**Comment by mostofi** [comment]
I feel slightly nervous about putting a default value for `fermi_energy`. Instead, could we use the value of `nfermi` to catch this occurrence? Eg,
```
    if(frozen_states) then
       if(nfermi>0) then
          kubo_freq_max        = dis_froz_max-fermi_energy_list(1)+0.6667_dp
       else
          kubo_freq_max        = dis_froz_max+0.6667_dp
       endif
    elseif(allocated(eigval)) then
       kubo_freq_max        = maxval(eigval)-minval(eigval)+0.6667_dp
    else
       kubo_freq_max        = dis_win_max-dis_win_min+0.6667_dp
    end if
```
A similar if test could be put where `fermi_energy_list` is printed to the output file?

**Comment by giovannipizzi** [comment]
Ok for me. In this case, then, I am not sure if it is a good idea to allocate fermi_energy_list anyway, when we read that variable, if fermi == 0. However, I'm not sure why that part of code was added, probably there was a problem without it? Maybe @ivosouza0 knows? (I think he was the one to add that comment)
