### ISSUE TITLE
Thresholds in ws_distance.F90

### ISSUE THREAD

**Issue by greschd** [wannier-developers/wannier90#101]
Email conversation: 
On Thursday, February 16, 2017 1:34:42 PM CET Dominik Gresch wrote:
> Thank you very much for your reply. Indeed, increasing the tolerance (in
> my case, to about 7.d-4) fixes this issue. I changed the code such that
> the tolerance can be given as an input parameter, see here:
> https://github.com/greschd/wannier90/tree/irdist_ws_tol
>
> First of all, do you think this is useful / necessary in general? If
> yes, are there other places in ws_distance.F90 where the tolerance
> should be changed accordingly? From glancing over the code I would guess
> maybe eps = 10 * irdist_ws_tol would make sense. Of course we could also
> let the user set eps and use irdist_ws_tol = eps / 10 . Please let me
> know what you think about this.

@paulatz wrote:

All the thresholds are inside ws_distance, there should be nothing outside of 
this file, which is good.

You are right that the various thresholds should be consistent, although I'm 
not sure it is trivial to do because some are measured in direct lattice 
units, other in fractional units.

In particular :
1. in R_ws_sc_equiv, line 235, we are accepting a **relative** error of 10^-5 in 
cartesian coordinates (coordinate system is important for anisotropic 
lattices)

2. in ws_translated_dist, line 157 we require an **absolute** precision of 10^-6 
in fractional coordinates.

If I remember correctly, I put this second check in order to spot bugs in the 
code, but now I think the check in ws_translate_dist could just be removed.

I think it could be a good idea to have the threshold value in R_ws_sc_equiv 
be an input parameter, and maybe default to something larger than 1.d-5

Also, I'm not sure that using a relative threshold, instead of an absolute 
value is justified, because it would require the centres of the WFs to be less 
accurately equivalent when using finer grids of k-points.

**Comment by greschd** [comment]
I would suggest the following: 
* Change the first test from relative to absolute, and making it configurable with a sensible default value. I think this is what the end user should care about -- how similar should the distances be to be considered equivalent.
* Keep the second test, but change the value such that it's really just a sanity check and should never fail, even considering numerical inaccuracies (something like 0.05). As far as I can see, this is just to test that rounding to the nearest integer doesn't change the value too much.

**Comment by greschd** [comment]
Of course we also need a good name for the input flag. Some candidates:
- ``ws_dist_tol``
- ``ws_distance_tol``
- ``ws_dist_equiv``
- ``ws_distance_equiv``
- ``ws_dist_equiv_tol``
- ``ws_distance_equiv_tol``

**Comment by giovannipizzi** [comment]
Fixed in #109
