### ISSUE TITLE
Strange use of utility_zgemm

### ISSUE THREAD

**Issue by ponweist** [wannier-developers/wannier90#103]
In _src/wannierise.F90_, lines 2482 and 2506, `utility_zgemm` is used in a strange way:

The matrices `u0` and `u_matrix` are of dimension `(num_wann,num_wann,num_kpts)`, however `utility_zgemm` assumes a shape of `(num_wann,num_wann)`.

The computation thus effects only the first k-point (i.e. the matrices `u0(:,:,1)` or `u_matrix(:,:,1)`). Is this intended?

```fortran
  2480         if (ldump) then
  2481            uc_rot(:,:)=cmplx(ur_rot(:,:),0.0_dp,dp)
  2482            call  utility_zgemm(u_matrix,u0,'N',uc_rot,'N',num_wann)
  2483            call param_write_chkpt('postdis')
  2484         endif
  2485
  2486         if (conv_window.gt.1) call internal_test_convergence_gamma()
  2487
  2488         if (lconverged) then
  2489            write(stdout,'(/13x,a,es10.3,a,i2,a)') &
  2490                 '<<<     Delta <',conv_tol,&
  2491                 '  over ',conv_window,' iterations     >>>'
  2492            write(stdout,'(13x,a/)')  '<<< Wannierisation convergence criteria satisfied >>>'
  2493            exit
  2494         endif
  2495
  2496      enddo
  2497      ! end of the minimization loop
  2498
  2499      ! update M
  2500      do nn = 1, nntot
  2501         sqwb=1.0_dp/sqrt(wb(nn))
  2502         m_matrix(:,:,nn,1)=sqwb*cmplx(m_w(:,:,2*nn-1),m_w(:,:,2*nn),dp)
  2503      end do
  2504      ! update U
  2505      uc_rot(:,:)=cmplx(ur_rot(:,:),0.0_dp,dp)
  2506      call  utility_zgemm(u_matrix,u0,'N',uc_rot,'N',num_wann)

```

**Comment by mostofi** [comment]
Dear Thomas,
I suspect this is in the gamma-only branch of the code, ie, the branch that is invoked when num_kpts=1.
Best wishes,
Arash

—
Arash Mostofi — www.mostofigroup.org<http://www.mostofigroup.org>
Director, CDT in Theory and Simulation of Materials
Imperial College London



On 2 Mar 2017, at 15:50, Thomas Ponweiser <notifications@github.com<mailto:notifications@github.com>> wrote:


In src/wannierise.F90, lines 2482 and 2506, utility_zgemm is used in a strange way:

The matrices u0 and u_matrix are of dimension (num_wann,num_wann,num_kpts), however utility_zgemm assumes a shape of (num_wann,num_wann).

The computation thus effects only the first k-point (i.e. the matrices u0(:,:,1) or u_matrix(:,:,1)). Is this intended?

  2480         if (ldump) then
  2481            uc_rot(:,:)=cmplx(ur_rot(:,:),0.0_dp,dp)
  2482            call  utility_zgemm(u_matrix,u0,'N',uc_rot,'N',num_wann)
  2483            call param_write_chkpt('postdis')
  2484         endif
  2485
  2486         if (conv_window.gt.1) call internal_test_convergence_gamma()
  2487
  2488         if (lconverged) then
  2489            write(stdout,'(/13x,a,es10.3,a,i2,a)') &
  2490                 '<<<     Delta <',conv_tol,&
  2491                 '  over ',conv_window,' iterations     >>>'
  2492            write(stdout,'(13x,a/)')  '<<< Wannierisation convergence criteria satisfied >>>'
  2493            exit
  2494         endif
  2495
  2496      enddo
  2497      ! end of the minimization loop
  2498
  2499      ! update M
  2500      do nn = 1, nntot
  2501         sqwb=1.0_dp/sqrt(wb(nn))
  2502         m_matrix(:,:,nn,1)=sqwb*cmplx(m_w(:,:,2*nn-1),m_w(:,:,2*nn),dp)
  2503      end do
  2504      ! update U
  2505      uc_rot(:,:)=cmplx(ur_rot(:,:),0.0_dp,dp)
  2506      call  utility_zgemm(u_matrix,u0,'N',uc_rot,'N',num_wann)

**Comment by ponweist** [comment]
Thanks for having a look!
