### ISSUE TITLE
Move Documentation and Tutorial to web page

### ISSUE THREAD

**Issue by mostofi** [wannier-developers/wannier90#119]
+ Add a troubleshooting section
+ Move FAQ and troubleshooting to a webpage, rather than in the User Guide
+ Make an HTML version of User Guide and Tutorial

**Comment by giovannipizzi** [comment]
I'm working on https://github.com/wannier-developers/wannier90-docs to see if we can use GitHub pages + Jekyll

**Comment by giovannipizzi** [comment]
Fixed in #470
