### ISSUE TITLE
Run with only parts of the projections given in the .amn file

### ISSUE THREAD

**Issue by greschd** [wannier-developers/wannier90#131]
Dear all,

As far as I know, it's not currently possible to 're-use' the .amn file when changing the projections -- which means the first-principles code needs to be re-run. Since this can take a lot of time, I propose the following syntax to allow re-using the files:

* Add an optional input block (let's call it ``select_projections`` for now) with the same syntax as the ``projections`` block.
* If ``select_projections`` is not given, everything stays as it is
* If ``select_projections`` is given, the ``projections`` block is used to determine which projections are in the .amn file, and the ``select_projections`` block tells us which of these are actually to be used. 

This means that ``select_projections`` could be an arbitrary subset of ``projections`` without changing the .amn file.

Please let me know what you think about this.

**Comment by mostofi** [comment]
Dear Dominik
To regenerate the projections, as long as you have saved the wavefunction
data, you should only need to calculate the overlaps and not the whole
electronic structure calculation again. In any case, this is an interesting
idea. There are some consistency checks that need to be thought about with
relation to the num_wann input parameter and depending on whether or not
the code is being run with the -pp command line option. Worth considering
though.
Best wishes,
Arash

**Comment by greschd** [comment]
Dear Arash,
Thanks, I actually had not considered this. However, I'm still in favour of adding such an option, in particular since it can take quite a while for the first-principles code to start up and re-do the projections (especially for large systems). Also, I've found that there's quite a performance hit (at least in VASP) for keeping the wave functions.
If you don't mind, I'll try to create an implementation for this, together with @quanshengwu.
Best,
Dominik

**Comment by greschd** [comment]
Hi Arash,
No, I haven't looked into this any further so far. I still think it could be useful, but it's not very high in priority for me.
Best,
Dominik
