### ISSUE TITLE
Problem in restart after merging the parallel code

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#133]
From Arash:
With the benzene example, if I run a wannierisation, and then do a second run setting "restart = wannierise” (or indeed plot) I get an error 
```
forrtl: severe (24): end-of-file during read, unit 11, file /export111/work/aam/w90-examples/example12-val/benzene.chk
```

Or:
example01, example02 etc: instead of the end-of-file error on reading .chk files, I sometimes get the following error on the first cycle of the restart:
```
Cycle:      1
 wann_main: ZHEEV in internal_new_u_and_m failed, info=            3
            trying Schur decomposition instead
 wann_main: SCHUR failed, info=            4
 Exiting.......
 wann_main: problem computing schur form 1
```

**Comment by jryates** [comment]
I think this is one problematic part of the code. In the comms_gatherv there is a reference to m_matrix which should be m_matrix_1b. This fixes the lead restart on my machine. 
 However, this is nothing to do with the gamma-point code, so the original issue must be something different. I can't reproduce any problems with the benzene example (various compilers, valgrind etc).

  do nn = 1, nntot
      m_matrix_1b_loc=m_matrix_loc(:,:,nn,:)
      call comms_gatherv(m_matrix_1b_loc,num_wann*num_wann*counts(my_node_id),&
                 m_matrix,num_wann*num_wann*counts,num_wann*num_wann*displs)
      call comms_bcast(m_matrix_1b(1,1,1),num_wann*num_wann*num_kpts)
      m_matrix(:,:,nn,:)=m_matrix_1b(:,:,:)
    end do!nn

**Comment by giovannipizzi** [comment]
Not fixed yet... (see https://travis-ci.org/wannier-developers/wannier90/jobs/311536683)

**Comment by jryates** [comment]
I think the test is wrong. The problem was not with reading the chk file, it was with writing it. So the test has a wrong chk file.

**Comment by giovannipizzi** [comment]
Interesting, thanks! I'll see if I can fix this with a new chk file.

**Comment by giovannipizzi** [comment]
It was even more simple than that... there was no reference file! I committed and created a PR so we have also this test case in, feel free to merge if it's OK. Thanks!
