### ISSUE TITLE
Large matrices and commented -heap-arrays in the make.inc

### ISSUE THREAD

**Issue by AntimoMarrazzo** [wannier-developers/wannier90#135]
What follows is valid and tested for ifort, but I guess this is what most people use...
When dealing with large systems (hence large matrices), wannier90 can crash in segmentation fault without giving hints to what happened (actually a memory issue).
Compiling with the -heap-arrays option solves it (it puts arrays on the heap instead of the stack), but I guess "inexperienced" users would struggle a lot before finding this out.
I was thinking to put a comment line in the config/make.inc.ifort suggesting to try -heap-arrays if the code crashes in segmentation fault when dealing with large matrices. I would not make -heap-arrays default, as it usually slows down a bit the calculations.
What do you think?
Antimo

**Comment by jryates** [comment]
On 1 May 2017, at 11:00, Antimo Marrazzo <notifications@github.com> wrote:

> What follows is valid and tested for ifort, but I guess this is what most people use...
> When dealing with large systems (hence large matrices), wannier90 can crash in segmentation fault without giving hints to what happened (actually a memory issue).
> Compiling with the -heap-arrays option solves it (it puts arrays on the heap instead of the stack), but I guess "inexperienced" users would struggle a lot before finding this out.
> I was thinking to put a comment line in the config/make.inc.ifort suggesting to try -heap-arrays if the code crashes in segmentation fault when dealing with large matrices. I would not make -heap-arrays default, as it usually slows down a bit the calculations.

Antimo,

 Thanks for this. What you propose is sensible for a short term fix.

 However, I think we need to get to real issue - why are large arrays put on the stack rather than heap. Usually this caused by automatic declaration of arrays. We should only ever use automatic arrays for fixed size quantities (i.e. things that don’t scale with the system). I can see that the site symmetry code is very bad for this - and needs some work. At least one has crept into disentangle.
 Can you tell us a bit more about the jobs that crash - what task are they doing - how many WF and how many kpts.

 Thanks
  Jonathan

**Comment by AntimoMarrazzo** [comment]
Thanks Jonathan,
my job was a disentaglement of a 43 atoms system, 8x8x3 k-points grid, 124 Wannier functions out of 240 bands. Indeed not standard calculation (I need to get a very accurate wannier hamiltonian of a periodic large cell), but still. On one of the epfl clusters, the code crashed right after disentaglement while on my workstation it crashed later while interpolating bands. The -heap-arrays option solved it on both.

**Comment by jryates** [comment]
> On 1 May 2017, at 17:34, Antimo Marrazzo <notifications@github.com> wrote:
> 
> Thanks Jonathan,
> my job was a disentaglement of a 43 atoms system, 8x8x3 k-points grid, 124 Wannier functions out of 240 bands. Indeed not standard calculation (I need to get a very accurate wannier hamiltonian of a periodic large cell), but still. On one of the epfl clusters, the code crashed right after disentaglement while on my workstation it crashed later while interpolating bands. The -heap-arrays option solved it on both.
> 
> 

Would there be an easy way for me to get access to the eig / win / mmn / amn files so that I can try to reproduce this locally. 

 Thanks
  Jonathan

**Comment by AntimoMarrazzo** [comment]
Sure, I will put them on Dropbox and send you a link privately. 
Thanks.
 Antimo

**Comment by AntimoMarrazzo** [comment]
After a long time, I cannot find the relevant files anymore - probably it is better to close the issue for now....
