### ISSUE TITLE
wannier90.amn Issue

### ISSUE THREAD

**Issue by sfragkos** [wannier-developers/wannier90#136]
Hello
I can't get wannier90.amn file from VASP. I tried  LWRITE_MMN_AMN but it didn't work.
I use the Wannier90 1.2 version.
Anyone knows why?

**Comment by sfragkos** [comment]
if anyone knows the answer please tell me because it's ugrent

**Comment by jryates** [comment]
On 5 May 2017, at 08:29, sfragkos <notifications@github.com> wrote:

> if anyone knows the answer please tell me because it's urgent

I don’t believe any of the wannier90 developers use VASP - so we cannot help you.

The most appropriate place to send your question will be the VASP forum.
You might also post your question to the Wannier90 mailing list.

 However, no one will be able to answer your question unless you provide more information (what are you trying to do, what were your inputs, what was the error message etc etc)

Jonathan
