### ISSUE TITLE
hamiltonian_write_rmn and hamiltonian_write_tb should give the same results

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#175]
See description of PR #168 
I open this issue so discussions can happen here

**Comment by ivosouza0** [comment]
I agree with the proposed changes.

**Comment by giovannipizzi** [comment]
@ivosouza0 does it mean that the PR can be merged? Or you want someone else to check?

**Comment by ivosouza0** [comment]
Yes, I think it is ready to be merged. I would have done it myself, but it
didn't look like I could do it (I was not a reviewer?)
