### ISSUE TITLE
Update default values for input flags, rename flags

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#197]
When we release a new version, if we bump to 3.0, it might be a good occasion to change some of the defaults when needed.
Things that we could do:

- [x] use_ws_distance to True by default

(Add above other possibilities)

**Comment by jryates** [comment]
iprint is not the best keyword. Verbosity might be better "low, default, medium, high" say

**Comment by giovannipizzi** [comment]
@mostofi suggests: maybe `guiding_centres` on by default?

**Comment by giovannipizzi** [comment]
Some decisions:
- [ ] we will set `use_ws_distance` to True (check #210 first, though)
- [ ] we will not set `guiding_centres` to True by default because there are some new modes that do not explicitly specify the projections (see e.g. SCDM) - however we'll document it better and put it also in the FAQ
- [ ] I'm going to check with a dense grid (e.g. 15x15x15 on Si) if having a very large num_shells is problematic, otherwise I'll increase it
- [ ] We will not rename `iprint` but improve the docs to say what the number means and the max value.

**Comment by giovannipizzi** [comment]
working in [the giovannipizzi/wannier90 - fix_197_new_defaults branch](https://github.com/giovannipizzi/wannier90/tree/fix_197_new_defaults)
