### ISSUE TITLE
changed behaviour of guiding_centres  in recent versions

### ISSUE THREAD

**Issue by gibertini** [wannier-developers/wannier90#222]
When considering cells with a large amount of vacuum and atomic positions around the centre of the cell, the minimisation procedure sometimes has issues and the spreads become quite large.
This applies for instance to 2D materials that extend along the xy plane and are centred at z = 0.5 (in crystal units).
I was always able to solve this problem in the past by using "guiding_centres = true".
I noticed that this is no longer the case in recent development versions.
In particular the latest versions (irrespective of the value of guiding_centres, true or false) provide the same wrong result as the old versions with guiding_centres = false, as if its effect would be now "disabled". 

I'm providing here a very simple example that shows this issue ([test_guiding_centres.tar.gz](https://github.com/wannier-developers/wannier90/files/2699903/test_guiding_centres.tar.gz)).
It's a one-dimensional chain of 10 Na atoms, sampled at gamma only. 
Up to version 2.1 the code finds a good minimum, with reasonable spreads. In the development version instead the spread is unphysically high.

I tried to perform a check on when the change in the behaviour was introduced using git bisect and this script ([test_revision.txt](https://github.com/wannier-developers/wannier90/files/2699859/test_revision.txt)).
I simply ran
`git bisect start`
`git bisect bad develop`
`git bisect good v2.1`
`git bisect run ./test_revision.sh`
but unfortunately many commits are skipped because the code ends with a segmentation fault when running my example, so that I'm left with more than 40 commits that cannot be further bisected:
a6706bab17b4fd42c9ce403c30dd366eb621cff8
66e8d5b624179eb55338fd15e70b3a923373673d
fb629b112892b4772fee3c2ca37244ae0e0b0f30
01786409ada479d3140892d11e3366f4caa3fc6c
6b424608b23c3f5e9de880c5e0fcf8d70b5a2ac3
b04258a2aa408965f5883384dd140de5487f24f2
fb96501c5a8680d961efff89b543a0427bafd826
00799a4fcb73f1ae6e3303d16d7a7561e8c0349e
aaf6b22ec83c7c5dd7fdc17ca73648202ef75874
2cd876e2d60b42e96fe24aa75b5261a7b0a183f3
af87eb87107183a875947dc1eec79f3052fba3c7
48050b8b4f9e6ff378f9e9404d7e01fea2e30dba
b98bd7be70091812e5407758cc8db47212a6dea7
0f2a17a6f2370215bc35d289b175e73f84facd32
25275e6f2dd97b1cc456dc0b8db7700684e0763a
484423f341385988995de612ff81692f9cb5e59d
da88cbbb63b1685722c68aa1b8b0ae2eeb5cb4de
7510b202cd16af106d2cac21a58152d686681fc9
a714cee25c4ae8ebdb04c9b244d2fa9160f16da4
43eeb6017728daaa27daa5c3157f4eb524277b39
7fd4df551b34cc00233c16549402d0922aa31c4c
268ff15871723effeb5e729577d7b361d1d4e08e
3954960fc41b00edf622a6286afb9aed48abf1d8
14fc136d9af36a7585ff385d4531aa841bfb2fa0
fcf2d2d46ebed9324938ad49773a5391a41db824
16043ac29d2756a59fe34e950d71f9e0a6c996b5
ee9ea818295eb0d7042d569383a8e91ecf8993f6
5539b3c3610443e095bb93d56147a4abf0fd2bed
cd114f326d6a61c189058b51ce39a9b54f6b7c13
14c3a8d92c7e4d38effd10411b7d5fb30990625d
6b446cceba381b98c179e5c06c174bf5dcdfea79
9e56241e81266ffeb15e0eeb29e329634fd0fd1f
bc6393c18877d54d68ce138f0614a89d18a53c88
23d9143e2ad9b3721b38b9456935d2083160fb15
55577079b1e4f1dc21f09e5dcca5fd5ca325f3dc
6aac864c2abd603d8e79047ba0e5d17f9044c5f6
aaeba5420a6e8849277b9f85a4a54984b10bb5a6
5d37feb873eda765bdf0a81fdcf3d7be329d8f35
61a36590133d4e565c1f3f4ea283d8c89f4f0380
3612ab06bab55a2031d2e49f9b7f8deb59088c76
548d18eec8500b1f3f659c868b83bc9d1c279fa7
9125408b41c8fd4915097cfcbbade4044979e149
b8082ae9f8a6adc158e6c584f7146bb7307a2d09
6dbd86bb7a301a33de43a99697da5f5ed7cd381a

**Comment by giovannipizzi** [comment]
Thanks a lot Marco @gibertini! I think that @jryates already spotted the problem and prepared a PR

**Comment by giovannipizzi** [comment]
Fixed in #223
