### ISSUE TITLE
Difference between Executable Mode and Library Mode

### ISSUE THREAD

**Issue by zhcui** [wannier-developers/wannier90#257]
Hi all,

I find that there are some differences between the normal executable mode and library mode, e.g. only serial mode is supported and the settings of `num_bands` seems different.

Before I use it, I would like to ask some questions about the lib mode:
(i) Does the library mode gives exactly the same result as that in the normal mode? Previously there is some bug in the lib mode, is it fixed recently?
(ii) What functionalities are not supported in the lib mode, but are supported by the normal mode?

Thank you very much!

Best,
Zhihao

**Comment by jryates** [comment]
We are not aware of any bugs in the v3.0 library mode. Library mode should give identical results to the standalone Wannier (if it doesn't, that is a bug, which should be reported).
  Library mode will conduct the disentanglement and wannierisation steps in serial (parallel is not implemented in library mode). All of the properties calculated from postw90.x are not available in library mode, although one could run postw90.x after a run in library mode.

**Comment by zhcui** [comment]
Hi Jonathan,

Thanks for your answer. 
I tried some simple cases, the normal mode and the lib mode indeed give exactly the same results.

Best,
Zhihao
