### ISSUE TITLE
Problem (precision) with the SHC tests

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#269]
The new SHC tests (introduced in #264 by @qiaojunfeng) are failing on some compilers, see:

http://130.186.13.169:8010/#/builders/15/builds/20/steps/5/logs/stdio

http://130.186.13.169:8010/#/builders/12/builds/26/steps/5/logs/stdio

http://130.186.13.169:8010/#/builders/18/builds/22/steps/6/logs/stdio

Is this expected (and increasing the threshold in the tests is ok) or does it hint at a bug?

**Comment by qiaojunfeng** [comment]
It seems that all the errors are less than 1e-2 relative to the benchmark values. I don't have much experience in these precision issues of compilers, but from a physical point of view, these results are acceptable.

**Comment by giovannipizzi** [comment]
Fixed in #273

**Comment by giovannipizzi** [comment]
I'm actually reopening this - there are still two tests failing:
- http://130.186.13.169:8010/#/builders/18/builds/26
- http://130.186.13.169:8010/#/builders/7/builds/27
