### ISSUE TITLE
three suggestions

### ISSUE THREAD

**Issue by hjunlee** [wannier-developers/wannier90#280]
Dear all:

I have three things (I believe) worth addressing in the future.
I believe that all of them are not difficult to implement.

(1) Currently, many functionalities, for instance the plotting routines, etc, are not parallelized; I guess that now only the root node takes care of them. In order to deal with complex cases [ex) plot of Fermi surface on the dense k grids] more efficiently, it is worth while to parallelize such routines.

(2) use of external FFT library: Many routines in W90 rely on the FFT. I believe that the use of optimized FFT library can speed up the calculations in many cases. Of course, in this case, we need some wrappers due to the different flavors of FFT library.

(3) example for the use of only the irreducible k points:
Even though I did the similar thing independently, recently the feature of using only the irreducible k grids for W90 (open_grid.x) is implemented and there is an example ( https://gitlab.com/QEF/q-e/tree/develop/PP/examples/W90_open_grid_example ).

From experience with my own implementation such feature is very useful since we can avoid using the full k grids and similar features are available in other DFT codes.
Thus, I think that it is worth while to include or mention the example of using open_grid.x in the example or tutorial.

Sincerely,

Hyungjun Lee

**Comment by jryates** [comment]
Thanks for the interesting suggestions!

1) You are correct. The only reason for this is historic: we intended postw90.x to be an efficient parallel code. We left some of the original functionality (fermi-surface plotting, band-structures and transport) in the serial wannier90.x. Now wannier90.x uses MPI there is no reason why those properties are serial. Before fixing this, we need to decide which of them should move to postw90.x and which stay in wannier90.x

2. I don't think we do make use of FFTs.

3. I didn't know about this routine. Yes, it would be good have an example in the tutorial. Of course, a faster approach would be do the overlaps with the IBZ and then unfold - but that involves more work.

**Comment by hjunlee** [comment]
Dear Jonathan Yates:

Thank you for your feedback.

Regarding 2, I meant that many routines in W90 and postW90 use the Fourier transform (not FFT, very sorry for the typo) and so I just guessed that we could speed up if we used the external FFT library.

Regarding 3, I thought that for the evaluation of Mmn we always need explicitly rotated wave functions while we could do the thing similar to unfolding by use of the expression of rotation of the spherical harmonics (like in the symmetrization of the product of psi and projector in USPP or PAW) for Amn. In any case, thanks for reminding me of unfolding.

**Comment by giovannipizzi** [comment]
Dear @hjunlee, I am going to move each point in a separate issue so it's easier to track their progress independently, and I will close this one.

In particular:
- point (1) [plotting parallelisation] -> #318 
- point (2) [FFT routines] -> I am not creating an issue. Currently, many of the Fourier transforms need to be done "by hand" since we have to transform entire matrices and these would not fit in memory. If you have a clear suggestion of a place where a (F)FT routine could help, feel free to suggest with a specific example (maybe in a new issue).
- point (3) [open_grid.x] -> #317
