### ISSUE TITLE
calculation of spin hall conductivity (SHC) & spin berry curvature 

### ISSUE THREAD

**Issue by nilcm90** [wannier-developers/wannier90#286]
Dear developers

I am trying to reproduce the results for spin hall conductivity (SHC) & spin berry curvature of Pt as given in arXiv:1907.09788 (2019) using github example29.

I am using same Pt.win & others file as given in example29.

But unfortunately, during post processing I am getting an error of **"value of berry_task not recognised in param_read".**
Can you please kindly guide me how to resolve this issue ?? I will be grateful to you for  your kind help.
Thank you.

**Comment by qiaojunfeng** [comment]
Which version of Wannier90 are you using? What do you set at `berry_task`? It should be `berry_task = eval_shc` for calculating SHC.

**Comment by nilcm90** [comment]
I am using wannier90, version  3.0.0. I have set **berry_task = eval_shc** for calculating SHC as given in **example29 for Pt**. 
I have attach the **.win** and **.wpout** file here. Please have a look. 

[Pt.zip](https://github.com/wannier-developers/wannier90/files/3488562/Pt.zip)

**Comment by qiaojunfeng** [comment]
The SHC code is available in the develop branch, not in the latest release. Your uploaded Pt.zip file is empty, so I can't find out if other problems exist in your input file. Can you please rerun your calculation with the latest develop branch?

**Comment by sfragkos** [comment]
Hello people!
Is there any version where I can calculate SHC and spin Berry curvature?
Thank you

**Comment by qiaojunfeng** [comment]
> Hello people!
> Is there any version where I can calculate SHC and spin Berry curvature?
> Thank you

Try the develop branch:
https://github.com/wannier-developers/wannier90/archive/develop.zip
and have a look at the directory `examples/example29` and the corresponding tutorial at  `doc/compiled_docs/tutorial.pdf`

**Comment by sfragkos** [comment]
> > Hello people!
> > Is there any version where I can calculate SHC and spin Berry curvature?
> > Thank you
> 
> Try the develop branch:
> https://github.com/wannier-developers/wannier90/archive/develop.zip
> and have a look at the directory `examples/example29` and the corresponding tutorial at `doc/compiled_docs/tutorial.pdf`

Thank you very much!
I tried it but I get the following error _"value of berry_task not recognised in param_read"_
I have tried both **berry_task = eval_shc** and **berry_task = shc**
Do you know how can I solve this problem?

**Comment by qiaojunfeng** [comment]
> > > Hello people!
> > > Is there any version where I can calculate SHC and spin Berry curvature?
> > > Thank you
> > 
> > 
> > Try the develop branch:
> > https://github.com/wannier-developers/wannier90/archive/develop.zip
> > and have a look at the directory `examples/example29` and the corresponding tutorial at `doc/compiled_docs/tutorial.pdf`
> 
> Thank you very much!
> I tried it but I get the following error _"value of berry_task not recognised in param_read"_
> I have tried both **berry_task = eval_shc** and **berry_task = shc**
> Do you know how can I solve this problem?

You should download the link that I pasted and compile it. The SHC code is available only in this version. The correct input parameter is `berry_task = eval_shc`.

**Comment by sfragkos** [comment]
> > > > Hello people!
> > > > Is there any version where I can calculate SHC and spin Berry curvature?
> > > > Thank you
> > > 
> > > 
> > > Try the develop branch:
> > > https://github.com/wannier-developers/wannier90/archive/develop.zip
> > > and have a look at the directory `examples/example29` and the corresponding tutorial at `doc/compiled_docs/tutorial.pdf`
> > 
> > 
> > Thank you very much!
> > I tried it but I get the following error _"value of berry_task not recognised in param_read"_
> > I have tried both **berry_task = eval_shc** and **berry_task = shc**
> > Do you know how can I solve this problem?
> 
> You should download the link that I pasted and compile it. The SHC code is available only in this version. The correct input parameter is `berry_task = eval_shc`.

Ok problem fixed. I guess the .spn file is generated from the pw2wannier90 interface, correct?
Is it possible for VASP users to generate that file?

**Comment by qiaojunfeng** [comment]
> > > > > Hello people!
> > > > > Is there any version where I can calculate SHC and spin Berry curvature?
> > > > > Thank you
> > > > 
> > > > 
> > > > Try the develop branch:
> > > > https://github.com/wannier-developers/wannier90/archive/develop.zip
> > > > and have a look at the directory `examples/example29` and the corresponding tutorial at `doc/compiled_docs/tutorial.pdf`
> > > 
> > > 
> > > Thank you very much!
> > > I tried it but I get the following error _"value of berry_task not recognised in param_read"_
> > > I have tried both **berry_task = eval_shc** and **berry_task = shc**
> > > Do you know how can I solve this problem?
> > 
> > 
> > You should download the link that I pasted and compile it. The SHC code is available only in this version. The correct input parameter is `berry_task = eval_shc`.
> 
> Ok problem fixed. I guess the .spn file is generated from the pw2wannier90 interface, correct?
> Is it possible for VASP users to generate that file?

Yes, the `.spn` file is generated by pw2wannier90. Maybe you can consult VASP developers to see if it can generate `.spn` file or not.

**Comment by stepan-tsirkin** [comment]
dear sfragkos (and others interested)

I sometimes produce .spn files from WAVECAR with the following script:
https://github.com/stepan-tsirkin/wannier90/blob/develop/utility/vaspspn.py

Note, that it uses only the plane-wave part of the  pseudo-wavefunction (no PAW projectors aded), I am not sure if it can make serious problems, but so far it gave no issues to me.

**Comment by sfragkos** [comment]
Dear stepan-tsirkin and others,

1) Thank you very much , this was very helpfull. Do you have any script for .dmn file also?

2) **kubo_smr_fixed_en_width tag** is need to avoid near zero number in the denominator of the kubo formula. But what if i want to study a _four-folded crossing point_? How much should I put the tag in this case? 
What is the expected value of _spin Ω_ at a four-folded crossing (Dirac) point ?
Is it zero, because the _spin Ω_ is opposite for the two bands that cross each other? Or, _spin Ω_ is infinite since the denominator is zero?

**Comment by giovannipizzi** [comment]
Dear all, I think the original question has been answered. I also mention that the feature will be available in the upcoming release 3.1, that should be published in the next few days.

If you want to continue the discussion on the additional questions:
- if it's a more physical question, we suggest to continue on the mailing list (and maybe report here the final answer to the questions, possibly)
- if it's more of a code issue, I suggest to open a new issues focused on the problem

Thanks a lot!

**Comment by Simba2805** [comment]
> > > > > > Hello people!
> > > > > > Is there any version where I can calculate SHC and spin Berry curvature?
> > > > > > Thank you
> > > > > 
> > > > > 
> > > > > Try the develop branch:
> > > > > https://github.com/wannier-developers/wannier90/archive/develop.zip
> > > > > and have a look at the directory `examples/example29` and the corresponding tutorial at `doc/compiled_docs/tutorial.pdf`
> > > > 
> > > > 
> > > > Thank you very much!
> > > > I tried it but I get the following error _"value of berry_task not recognised in param_read"_
> > > > I have tried both **berry_task = eval_shc** and **berry_task = shc**
> > > > Do you know how can I solve this problem?
> > > 
> > > 
> > > You should download the link that I pasted and compile it. The SHC code is available only in this version. The correct input parameter is `berry_task = eval_shc`.
> > 
> > 
> > Ok problem fixed. I guess the .spn file is generated from the pw2wannier90 interface, correct?
> > Is it possible for VASP users to generate that file?
> 
> Yes, the `.spn` file is generated by pw2wannier90. Maybe you can consult VASP developers to see if it can generate `.spn` file or not.

Dear all,

I am a VASP user. Using the wannier90.win file which is available in example29, as mentioned above I am also facing the same issue (the issue with which this thread initially started "param_read"). But when I compiled again my wannier90 with the link given in this thread for SHC I am getting the same but manipulated error "**_**Error: berry_task=shc and shc_method is not set**_**". After compilation, I am also getting this w90spn2spn.x. Do I need to use that? 

This is what I'm trying to do:
1. First I am creating a WAVECAR file from a regular SCF VASP run. 
2. I copy WAVECAR to another directory along with other VASP input files and INCAR I use LWANNIER90 = .TRUE. tag to create necessary files.
3. Here I create a wannier90.win file and then add necessary commands given in exampple29 to calculate SHC for my system.
4. I make another directory and copy all wannier90.* files and run the usual "**_wannier90.x wannier_**" to calculate SHC. But it returns the error I mentioned above.

**Comment by stepan-tsirkin** [comment]
@Simba2805 , 

first, you can combine 1 and 2 together

second, you need a wannier90.win  file already at your step 2, in order to specify the starting projections.

you also need to produce a `.spn` file, which can be done using a [script](https://wannier-berri.org/docs/vaspspn.html) which is now part of the [WannierBerri](https://github.com/wannier-berri/wannier-berri) project. 

> After compilation, I am also getting this w90spn2spn.x. Do I need to use that?

I do not think so : 
https://github.com/wannier-developers/wannier90/blob/528a67f8b38fceb2252f085877bb2ba9acece7fb/src/w90spn2spn.F90#L15-L17

> I am getting the same but manipulated error "Error: berry_task=shc and shc_method is not set"

did you make sure the following line is in your `.win` file?

https://github.com/wannier-developers/wannier90/blob/528a67f8b38fceb2252f085877bb2ba9acece7fb/examples/example29/Pt.win#L5

**Comment by supermanp** [comment]
> > > > > > Hello people!
> > > > > > Is there any version where I can calculate SHC and spin Berry curvature?
> > > > > > Thank you
> > > > > 
> > > > > 
> > > > > Try the develop branch:
> > > > > https://github.com/wannier-developers/wannier90/archive/develop.zip
> > > > > and have a look at the directory  and the corresponding tutorial at `examples/example29``doc/compiled_docs/tutorial.pdf`
> > > > 
> > > > 
> > > > Thank you very much!
> > > > I tried it but I get the following error _"value of berry_task not recognised in param_read"_
> > > > I have tried both **berry_task = eval_shc** and **berry_task = shc**
> > > > Do you know how can I solve this problem?
> > > 
> > > 
> > > You should download the link that I pasted and compile it. The SHC code is available only in this version. The correct input parameter is .`berry_task = eval_shc`
> > 
> > 
> > Ok problem fixed. I guess the .spn file is generated from the pw2wannier90 interface, correct?
> > Is it possible for VASP users to generate that file?
> 
> Yes, the file is generated by pw2wannier90. Maybe you can consult VASP developers to see if it can generate file or not.`.spn``.spn`

Dear developers

I am trying to use github example 25 .

I am using the same GaAS.win and other files as given in example 25. The version I am using is 3.1.

Running wannier90.x -pp GaAs as per step 3 of the tutorial, I am getting the error "berry_task value not recognized in param_read".
Can you please guide me on how to resolve this issue? I will be grateful if I can get your help.
Thanks.
