### ISSUE TITLE
wannier90.x : command not found

### ISSUE THREAD

**Issue by WannierUser12** [wannier-developers/wannier90#292]
wannier90.x : command not found. Got this error when I tried to run example. I've installed Quantum Espresso and other libraries that are needed. I can't find out what is problem.

**Comment by jryates** [comment]
Wannier90.x is the name of the compiled executable. So either 
a) you didn't compile wannier90.x
b) the executable isn't on your path - so you need to either reference it explicitly e.g. ../../wannier90.x or add it to a folder that is on your path.
 If you have issues with either of these you should consult your local computing support.

**Comment by WannierUser12** [comment]
> Wannier90.x is the name of the compiled executable. So either
> a) you didn't compile wannier90.x
> b) the executable isn't on your path - so you need to either reference it explicitly e.g. ../../wannier90.x or add it to a folder that is on your path.
> If you have issues with either of these you should consult your local computing support.

I have a second problem. If I copy wannier90.x to example folder it's works. So, can I make the wannier90.x work without specifying a path? I tried to add line "export PATH=$PATH:/home/konstantin/Загрузки/wannier90-3.0.0/" in .bashrc. It didn't work.

**Comment by jryates** [comment]
To be clear: this is a general linux question - there is nothing specific to wannier90 here.

Modifying the path should work (assuming your shell is bash). You can type 'env' to see if the path was modified correctly. Note that you need to either 'source ~/.bashrc' or logout and login to pick up your new changes to the bash configuration.

**Comment by WannierUser12** [comment]
Thank you so much! I will try.
