### ISSUE TITLE
Improving postw90 or rewriting it in python. 

### ISSUE THREAD

**Issue by stepan-tsirkin** [wannier-developers/wannier90#296]
related to #280 , but regarding the postw90.x 

Dear all,

in this issue I would like to outline some problems of performance of postw90.x, and how I am advancing to solve them in another code, which I wrote (and continue developing) in python. And I welcome interested people to collaborate with me in this direction.

A number of modules of postw90.x  (e.g. berry.f90, gyrotropic.f90, boltzwann.f90) evaluate an integral over the Brillouin zone of some quantity.  The speed of such calculations are not perfect for several reasons:

1)  symmetries of the system are not accounted for, so summation runs over all k-points, instead of restricting only to the irreducible ones

2) A major part of computational time is used by  fourier transform. Using FFT would speed up the calculations.

3) Adaptive refinement, which proved useful for AHC, is implemented only there. And implementation in other quantities requires copy-pasting. 

4) Calculation of AHC for multiple fermi levels slow down calculations a lot.

5) Use of parameter use_ws_distance=true (which is default since v3.0) slows down calculation, because it is used at every call of Fourier transform. Instead, there is a way to re-define the real-space quantities only once, before looping over k-points.

To overcome these issues I started a new project in python [https://github.com/stepan-tsirkin/wannier19](url).  I called in Wannier19 by the year of starting.  It is now in active development stage, and not well documented. (I am the only developer so far). 
But already it can calculate Anomalus Hall conductivity and orbital magnetization very fast with high k-point density. In fact all 5 issues listed above are implemented there.  

It might sound surprizing (to someone)  that a python code is faster than a fortran code. But using of efficient libraries ( basically, numpy which includes fft) makes the "slowness" of python insufficient. And the use of flexibility and object-oriented model makes it easier to implement smarter algorithms. 

Implementation of the same algorithms in Fortran is possible, in principle, but not obvious to me.  However, if someone  is motivated to improve postw90, feel free to do it by analogy with my python code, I will provide explanations.

On the other hand, those who are interested in doing accurate calculations of AHC, or whatever quantity which is already implemented in postw90 (or even might be implemented), please contact me and join me in working on Wannier19.

I also wonder if the community is interested in eventual merging Wannier19 into Wannier90. Although they are in different languages, and communicate which each other only via input-output files, (wannierization is done by the good old Wannier90),   but it would be good to keep them consistent. Anyway, that's only when wannier19 is really mature enough. 

Thanks to all, who read this long post to the end!
Stepan.

**Comment by hjunlee** [comment]
Dear Stepan:

Great suggestions! I totally agree with you in all aspects you mentioned.

Since I don't know python, I can't understand your implemented algorithms in your code.
I have two questions:

Regarding 1: I would like to know how to solve this issue.
Did you just assume the symmetry and evaluate the physical quantities on the remaining k grids by rotating those on the irreducible k grids using the symmetry operations?

Regarding 4: What are the bottlenecks? I also found one bottleneck and made a commit (https://github.com/wannier-developers/wannier90/pull/289). Is there another bottleneck you identified?

Sincerely,

Hyungjun Lee

**Comment by stepan-tsirkin** [comment]
Dear Hyungjun,

Rgarding 1: yes, essentially what you wrote. To be more specific, I first generate a list of k-points on a uniform mesh, assigning them equal weights.  Then looping over k-points, I check whether k-point Ki is equivalent to any k-point Kj, and if True, I remove Ki, transferring its weight to Kj.
In the end I sum the physical quantities evaluated at remaining k-points with proper weights, and finally symmetrize the result. (by taking an average over al operations of the symmetry group). I give the generators of the symmetry group manually, so i have controll on wha symmetries to use.

Regarding 4: Thank's for commit #289 . But there are also more things, even without refinement. 
Which are actually easy to implement also in postw90. 

4.1 - there are multiple unnecessary unitary rotations. Consider term J0.  
We evaluate it as : 
```
          imf_k_list(1, i, ife) = &
            utility_re_tr_prod(f_list(:, :, ife), OOmega(:, :, i))
```

In turn, f_list is obtained (in wan_ham.F90)  by unitary rotation of a diagonal occupation matrix 
in matrix form   f_list=U.occ_list.U^+   - this rotation is done for each Fermi level. 

On the other hand, using the properties of the trace we can write 

```
          imf_k_list(1, i, ife) = &
            sum( occ_list(:,  ife), OOmegaUUdiag(:, i) )
```
Where  OOmegaUUdiag - is the diagonal of the rotated matrix (U^+).OOmega.U
Thus the rotation of OOmega is done only once for all Fermi levels. 

Similar simplifications may be applied also to the J1 and J2 terms. ANd in the orbital magnetiation part also similar.

4.2 - when we loop over a fine grid of Fermi levels (for a particular k-point), most of the time the resulting AHC does not change, unless we cross the energy of some band. 
In fact, for a particular k-point, the AHC looks like a set of horizontal plateaus. Only after intergation over many points, we get a smooth curve.  Thus, the Idea is to evaluate only the changes at the Fermi levels, where bands are crossed. For the rest of fermi levels, the values of the previous fermi levels. Thus the evaluation time for many (say, ~10^4) Fermi levels will be paractically the same as for n fermi levels, where n is the number of bands in the Fermi level window(usually ~<10)


I hope you get the main idea, but do not hesitate to ask if something is unclear.

Regards,
Stepan.

**Comment by hjunlee** [comment]
@stepan-tsirkin Thank you very much for your kindly reply.
