### ISSUE TITLE
Band structure for random alloys

### ISSUE THREAD

**Issue by sfragkos** [wannier-developers/wannier90#297]
Hello developers and people,
Is it possible to perform band structure calculations for random alloys using Wannier90, like VCA or CPA?
If not, maybe someone has made an _unofficial_ implemention for it?
Thank you!

**Comment by giovannipizzi** [comment]
Dear @sfragkos, probably this is more a question for the mailing list, where more people can try to answer. I suggest that you post your question there. Thanks!
