### ISSUE TITLE
Spin Hall Conductivity tensor

### ISSUE THREAD

**Issue by sfragkos** [wannier-developers/wannier90#304]
Dear wannier90 developers and users,

The SHC σγαβ is a third-order tensor and represents the spin current along the α direction generated by an electric field along the β direction, where the spin current is polarized along the γ direction.

In the case of orthorhombic, cubic, etc, these three are probably orthogonal. But what happens in the case of a hexagonal or trigonal lattice, were the lattice vectors form an angle of 60 or 120 deg?

**So the question is, are α β and γ in the calculated SHC always orthogonal, no matter what the lattice symmetry is, or they adapt to the lattice vectors?**

Best regards,
Sotiris

**Comment by qiaojunfeng** [comment]
The velocity is calculated with `b` vector [Eq. (B1), PRB 56, 12847 (1997)], which is in Cartesian coordinate. Thus the 3 directions of SHC are always along the Cartesian axes.

**Comment by sfragkos** [comment]
Thank you for your answer.

Then in a hexagonal or trigonal system σxy should be different from σyx. Is this correct?
But this is not the case in my calculations... the two tensors seem to be just  σxy=-σyx

Best regards,
Sotiris

**Comment by qiaojunfeng** [comment]
> Thank you for your answer.
> 
> Then in a hexagonal or trigonal system σxy should be different from σyx. Is this correct?
> But this is not the case in my calculations... the two tensors seem to be just σxy=-σyx
> 
> Best regards,
> Sotiris

It also depends on how you position your lattice cell, e.g. for trigonal whose diagonal is along [111] direction then σxy=-σyx might still be true.

**Comment by mostofi** [comment]
Dear @sfragkos, thanks for the question but this may have been more appropriate for the mailing list where more people would have the opportunity to answer and benefit from the discussion. Thanks!
