### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by izaz-918** [wannier-developers/wannier90#316]
Hi 
I am trying to install wannier90. I copy make.inc.ifort from config to root directory and run make command. When I give make wannier command the following error occur.
make[1]: Nothing to be done for 'wannier'

**Comment by giovannipizzi** [comment]
Dear izaz-918, this is not an error. This typically means that the file has already been compiled. Please post further questions related to the usage of the code to the mailing list rather than on this issue tracker (reserved for code issues), thanks!

**Comment by izaz-918** [comment]
Dear sir
When I calculate the crystal field parameters for the example and give
wannier90.x -pp case 
command  in 3rd step the following error occur 
Error: examine the output/error file for details.
Please guide me to fix this error
