### ISSUE TITLE
Parallelise the plotting routines (or move them to postw90.x)

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#318]
As @hjunlee reports in #280:
> Currently, many functionalities, for instance the plotting routines, etc, are not parallelized; I guess that now only the root node takes care of them. In order to deal with complex cases [ex) plot of Fermi surface on the dense k grids] more efficiently, it is worth while to parallelize such routines.

The reason is these routines have been historically in wannier90.x, and this executable was not parallel until very recently (v3.0).
Originally, we were planning to move them to the parallel postw90.x where they are also more fitting as a 'post processing', but we decided to keep them to avoid to break compatibility with how users are used to run the code.

Even if we decide to keep them in the wannier90.x code, we can still parallelise them now, since the code is now parallel.

**Comment by qiaojunfeng** [comment]
already fixed in #370
