### ISSUE TITLE
Error: examine the output/error file for detail

### ISSUE THREAD

**Issue by izaz-918** [wannier-developers/wannier90#319]
Hi 
I am trying to calculate crystal field parameters (CFP) using wannier90. the following error occur 
Error: examine the output/error file for detail.

![Screenshot from 2020-02-26 04-31-21](https://user-images.githubusercontent.com/61352178/75279675-caf44480-582d-11ea-8336-34015d2e04c5.png)
. please guide me in this regards.

**Comment by giovannipizzi** [comment]
The explanation of the error is on the line above the one you selected - the name of the parameter changed and you need to use the new name.

In the future, please use the mailing list to get support; only post a new issue if you think it's a bug in the code. Thanks!
