### ISSUE TITLE
Combine the doc and docs diretories into one.

### ISSUE THREAD

**Issue by hongyi-zhao** [wannier-developers/wannier90#324]
Hi,

Currently, there are two directories under the project's root:

doc and docs

While there is only one file located in the directory docs: CONTRIBUTING.md

Maybe combine these two directories into one for concision and simplicity.

Regards

**Comment by jryates** [comment]
This was my fault: GitHub suggests that we have a contribution statement 
 "To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's root, docs, or .github folder."
  When I added this, it automatically created the docs directory - while our documentation has always been held in the doc folder.
 Assuming we keep this file perhaps the best thing is to move it to the root directory?

**Comment by hongyi-zhao** [comment]
It seems good to put it immediately under the root directory for attracting users attention.  OTOH, can also ref the some similar files under the root  directory for [linux kernel](https://github.com/torvalds/linux).

Regards
