### ISSUE TITLE
Improve the adaptive smearing

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#33]
Check in particular if the adaptive smearing implemented in BotlzWann works properly and then move the code also for the other postw90.x routines.

**Comment by mostofi** [comment]
Update documentation to reflect differences in smearing method.

**Comment by giovannipizzi** [comment]
I'm closing this, since there is already a comment in a footnote of the documentation in section 12.2.1 (files/seedname_boltzdos.dat) that clarifies this. It reads: 

> Note that in BoltzWann the adaptive (energy) smearing scheme also implements a
> simple adaptive k−mesh scheme: if at any given k point one of the band gradients
> is zero, then that k point is replaced by 8 neighboring k points. Thus, the final results 
> for the DOS may be slightly different with respect to that given by the dos module.
