### ISSUE TITLE
ERROR in wigner_seitz: error in finding Wigner-Seitz points

### ISSUE THREAD

**Issue by trumanmiguel** [wannier-developers/wannier90#331]
Hi Wannier90 developers, 

I have the above error. At first, I encountered "error in finding Wigner-Seitz points" in the hamiltonian_wigner_seitz subroutine when running wannier90.x. I increased ws_search_size from 2 to 4 and it works.

When I tried to run postw90.x, I get the above error. For some reason, the error message and the vectors are not fully printed out when I tried running postw90.x again.

I have attached the *.win, *.wout, *.wpout and a data file which contains tot and mp_grid from the wigner_seitz subroutine. 

[TaAs.win.txt](https://github.com/wannier-developers/wannier90/files/4671297/TaAs.win.txt)
[TaAs.wout.txt](https://github.com/wannier-developers/wannier90/files/4671281/TaAs.wout.txt)
[TaAs.wpout.txt](https://github.com/wannier-developers/wannier90/files/4671283/TaAs.wpout.txt)
[ws.txt](https://github.com/wannier-developers/wannier90/files/4671284/ws.txt)

Can someone kindly tell me why I have this error?

Thanks. 

Regards,
Truman

**Comment by giovannipizzi** [comment]
I think that in #216 the extension to `ws_search_size` was added here (and following lines):
https://github.com/wannier-developers/wannier90/blob/27d01d53d94530a5dd83e5622a23789b554b37a7/src/hamiltonian.F90#L548
but we forgot to do it for at least this function in postw90 here:
https://github.com/wannier-developers/wannier90/blob/5dda1325bd4e773afda78fba6720965810fa5253/src/postw90/postw90_common.F90#L1426

I don't know if there are more functions - unfortunately the two functions look more or less copy-pasted, with some differences - in the long term we might want to  try to unify them.

@gibertini @paulatz any feedback, or chance to make a PR to fix this? Or @trumanmiguel would you be able to apply the same changes as in #216 also to `postw90/postw90_common.F90` and check if they work, and ideally then make a pull request?

Thanks!

**Comment by gibertini** [comment]
Thanks for reporting this! 
Indeed @giovannipizzi is right and it should be sufficient to make the same changes as in #216 also in  `postw90/postw90_common.F90` (actually I thought I already did it at that time..apologies).
I will fix it as soon as possible. If instead @trumanmiguel is already working on this, please let me know so that we don't do the same thing twice.
