### ISSUE TITLE
The meaning of *hr* used in many keywords' names.

### ISSUE THREAD

**Issue by hongyi-zhao** [wannier-developers/wannier90#333]
Hi,

I noted that there are many keywords whose names include `hr`, say, `write_hr`, but I still cannot figure out the original meaning / unabbreviated form of it?

Any hints for this?

Regards

**Comment by giovannipizzi** [comment]
`H(r)`, the Hamiltonian in real space

**Comment by hongyi-zhao** [comment]
> `H(r)`, the Hamiltonian in real space

Really hard to figure out without your above note.

Currently, there are some keywords like this defined by wannier90 are not clearly explained about their names origins. I think things like this should be commented/touched up in wannier90's source code in the form which should be more convenient for users to remember and use.

**Comment by giovannipizzi** [comment]
Well, it's "implicitly" explained e.g. in Sec. 8.19 of the user guide, and in this code comment:
https://github.com/wannier-developers/wannier90/blob/2f4aed6a35ab7e8b38dbe196aa4925ab3e9deb1b/src/hamiltonian.F90#L446

If you feel that the comments could be more clear, we would appreciate a lot any PR to improve the current status!

**Comment by hongyi-zhao** [comment]
There are **many parameters** defined like this manner in the wannier's sourcecode which don't give user an intuitive conception based on their names.

Say, for this case, you said that:

`H(r), the Hamiltonian in real space`

So, I think we should give the definition and comment like:

`write_hamiltonian_hr()     !  Write the Hamiltonian in the real space's WF basis`

But the current definition and comment is as following:

`hamiltonian_write_hr()  !  Write the Hamiltonian in the WF basis`

IMO, if we define a parameter, the name of it should be consistent with its meaning expressed in natural language as much as possible.
