### ISSUE TITLE
One precision test fails on 2/5 of our clusters

### ISSUE THREAD

**Issue by ikirker** [wannier-developers/wannier90#341]
I'm trying to build Wannier90 as a library for use with [Elk](http://elk.sourceforge.net/), on behalf of a researcher.

We have a number of compute clusters, and we generally install software on all of them if we're installing it on any of them. (To maintain our own fragile grip on sanity.)

Using the `make.inc` below, and the versions of the Intel compiler and MKL shown below, three of the clusters finish the build successfully, but 2 out of 5 of our clusters fail a single test: `testpostw90_pt_kpathbandsshc - Pt.win`, with what *looks* like a minor accuracy failure. I'm not experienced enough in the domain to know whether that tolerance is set narrow or tight, though.

The two clusters where it fails have the same type of processor, that none of the three others does: Intel Xeon(R) CPU E5-2650 v4.

I'm *guessing* this is due to some optimisation in MKL that doesn't quite get the accuracy the tests require, but it would be useful to know if the authors consider this a problem or not.

Happy to provide any other information people would find useful.

----

Test failure:
```
tests/testpostw90_pt_kpathbandsshc - Pt.win: **FAILED**.
shc
    ERROR: absolute error 1.08e-02 greater than 1.00e-02. (Test: -8.1625987.  Benchmark: -8.1517891.)
shc
    ERROR: absolute error 1.08e-02 greater than 1.00e-02. (Test: -8.719545.  Benchmark: -8.7303551.)
```

`make.inc`:
```
#=====================================================
# For Linux with intel version 11/12 on 64bit machines
#=====================================================
F90 = ifort
COMMS=mpi
MPIF90=mpiifort
FCOPTS=-O2
LDOPTS=-O2

#========================================================
# Intel mkl libraries. Set LIBPATH if not in default path
#========================================================

LIBDIR = $(MKLROOT)/lib
LIBS   =  -L$(LIBDIR) -lmkl_core -lmkl_intel_lp64 -lmkl_sequential -lpthread
```

Software versions:
```
$ icc --version
icc (ICC) 18.0.3 20180410
Copyright (C) 1985-2018 Intel Corporation.  All rights reserved.

$ mpirun --version
Intel(R) MPI Library for Linux* OS, Version 2018 Update 3 Build 20180411 (id: 18329)
Copyright 2003-2018 Intel Corporation.
```

**Comment by qiaojunfeng** [comment]
Hi Ian, thanks for your report. I already increased the tolerance to `1e-1` in commit 0ec22d34f33a0dc5e86fa4ce7835de673a52bf15, but it was after release 3.1. So you can skip this failure.

**Comment by ikirker** [comment]
@qiaojunfeng Thank you, that's great. I'll add a bit to our scripted build to apply the wider tolerances via a patch from that commit.
