### ISSUE TITLE
Number of digits in the k-point index in eig, amn, and mmn files

### ISSUE THREAD

**Issue by hjunlee** [wannier-developers/wannier90#347]
Dear all:

The user of anyipeng in EPW forum reported the small issue with the number of digits in k-point index in the eig file generated by pw2wannier90.x ( https://forum.epw-code.org/viewtopic.php?f=3&t=1336 )

Shortly speaking, currently pw2wannier90.x can deal with the case with the k-point index with up to 5 digits; so he (or she) encountered the error when using large number of k points (in his (her) case, 24x24x24)
I realized that the same issue is present in amn, mmn, etc.

As all of you know, the fix is very simple, but I think that first we need to make a decision on the number of digits or adding the blanks between columns rather than increasing the number of digits.

Sincerely,

Hyungjun Lee

**Comment by qiaojunfeng** [comment]
Thanks! This is now fixed in the `develop` branch of QE, e.g.
- `amn`
    https://gitlab.com/QEF/q-e/-/blob/ea5b866818254ccf9ddf01652ff78a878f82f26e/PP/src/pw2wannier90.f90#L6619
- `mmn`
    https://gitlab.com/QEF/q-e/-/blob/ea5b866818254ccf9ddf01652ff78a878f82f26e/PP/src/pw2wannier90.f90#L3128
- `eig`
    https://gitlab.com/QEF/q-e/-/blob/ea5b866818254ccf9ddf01652ff78a878f82f26e/PP/src/pw2wannier90.f90#L6821
