### ISSUE TITLE
Accuracy of SHC calculation

### ISSUE THREAD

**Issue by jzzhang001** [wannier-developers/wannier90#354]
Now I am using Wannier90 for spin hall conductivity calculations. Here I want to know the numerical accuracy limit of the results in the unit of (hbar/e)*S/cm. Namely, when should I regard the result as a numerical error? Thanks for your kind reply.

**Comment by qiaojunfeng** [comment]
If you got good Wannier functions (low spreads, good band interpolation, and good spin operator interpolation, which you can check by doing a kpath plot coloured by a spin projection), and you could afford the computational cost, then by increasing the berry_kmesh density, the spin Hall conductivity could converge under 1 (hbar/e)*S/cm, or even further (requires very dense berry_kmesh).

**Comment by jzzhang001** [comment]
Got it. Thanks a lot.
