### ISSUE TITLE
Occupation of Wannier Functions

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#36]
To get the occupation of Wannier functions
See emails on April 3rd, 2013 on mailing list and related emails

**Comment by jryates** [comment]
Projected dos is already implemented. So the original title is a bit misleading.
 The issue here is to consider the occupation of the WF. Either by summing the projected DOS up to the Fermi level, or by calculating the trace of an occupation matrix.

**Comment by giovannipizzi** [comment]
For now, this is not a feature that we implement if there are not user requests for it.
