### ISSUE TITLE
About the SCDM

### ISSUE THREAD

**Issue by tsiayigong** [wannier-developers/wannier90#364]
Dear developers,
      Would you teach me how to obtain the mu and sigma for the SCDM calculation?
===========================
Thank you for your help

**Comment by giovannipizzi** [comment]
Dear @GJYAQXT, the issues are dedicated to discuss code problems and not to ask for help: use the mailing list for that. In any case, I suggest you study this paper: https://dx.doi.org/10.1038/s41524-020-0312-y and check this tutorial: https://github.com/wannier-developers/wannier-tutorials/tree/master/2020_03_Oxford/2a_scdm as well as this tutorial: https://aiida-tutorials.readthedocs.io/en/latest/pages/2020_Oxford/index.html#oxford-2020-homepage
