### ISSUE TITLE
Task is killed when calculating spin Hall conductivity.

### ISSUE THREAD

**Issue by kibgboomba** [wannier-developers/wannier90#366]
When I calculated spin Hall conductivity, the task was killed when the ".wpout" file output:

###############################################
   * Spin Hall Conductivity

     Fermi energy scan
 
 Calculation started
 -------------------------------
   k-points       wall      diff
  calculated      time      time
  ----------      ----      ----
       0%          0.0       0.0

################################################## 

And  the SupercomputerCenter output:

###############################################################
yhrun: error: cn362: task 0: Killed
yhrun: error: cn362: task 27: Killed
yhrun: error: cn362: task 11: Killed
yhrun: error: cn362: task 17: Killed
yhrun: error: cn362: task 7: Killed
yhrun: error: cn362: task 19: Killed
yhrun: First task exited 60s ago
yhrun: tasks 1-6,8-10,12-16,18,20-26: running
yhrun: tasks 0,7,11,17,19,27: exited abnormally
yhrun: Terminating job step 3085464.0
yhrun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 3085464.0 ON cn362 CANCELLED AT 2021-04-13T08:55:19 ***
yhrun: error: cn362: tasks 1,3,5,9,13,15,21,23,25: Killed
yhrun: error: cn362: tasks 2,4,6,8,10,12,14,16,18,20,22,24,26: Killed
##################################################################

there was no ".err" file. Can anyone tell me what's wrong? Thanks very much!

**Comment by qiaojunfeng** [comment]
Probably the memory was not enough, the job was killed by the job scheduling system.
