### ISSUE TITLE
Manual test-suite for pw2wannier90

### ISSUE THREAD

**Issue by jaemolihm** [wannier-developers/wannier90#369]
Currently, `pw2wannier90` is not automatically tested in the QE repository. I decided it would be a good to have a manual test-suite for the code. So, I created a repository for it: https://github.com/jaemolihm/pw2w90_test

It compares two QE builds (`QE_REF` and `QE_TEST`) and tests whether the output of `QE_TEST` is identical to that of `QE_REF`. It contains several test cases. The README file explains how to run tests by yourself. (Note that I am working on a k-point parallelization (a.k.a. pools) and some other refactoring and optimizations for `pw2wannier90` ([link](https://gitlab.com/jmlihm/q-e/-/tree/pw2wan)). So, the tests runs both with and without pools. It can be changed by modifing `RUN_SUFFIX_POOL` in the file `environment_variables`.)

Also, it contains a [code coverage report](https://raw.githack.com/jaemolihm/pw2w90_test/master/coverage/output/src/pw2wannier90.f90.gcov.html) (The report is for my modification of the pw2wannier90 code). The README also explains how to generate one.

I am sharing this here so that anyone could easily test their own modification of `pw2wannier90`. I would appreciate any feedback.

**Comment by hjunlee** [comment]
@jaemolihm Interesting work. Well, I am not clear about whether you already did it, but you can reduce a bit the number of evaluations in compute_mmn as you did in compute_orb: Mmn(k,b)=conjg[Mnm(k+b,-b)]

**Comment by giovannipizzi** [comment]
Thanks @jaemolihm ! This looks very useful.

Why don't you contribute it to the Quantum ESPRESSO main repository ([they use GitLab](https://gitlab.com/QEF/q-e) though, on GitHub there's only a mirror). This would be very useful for future updates to the code. And I think they use the same (or a very very similar) test code so hopefully it's not too much work to contribute it there.

**Comment by jaemolihm** [comment]
Hi @giovannipizzi , thanks for the comment. I agree that this kind of test should go to QE. The testing framework is a bit complicated, but I'll take a look.

Regarding the refactoring and optimization of the pw2wannier90 code I mentioned, it is a big change so I think Wannier90 developers should take a look before I try to merge it to QE. For that, I will open a separate issue or PR here when I am done.

Since there is nothing that should be done now in Wannier90, this issue can be closed.
