### ISSUE TITLE
Add command-line help

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#37]
To print:
- basic information on what are the possible command line options
- print some help when wannier is run without options
- add a `--dry-run` option to validate the input file
- add a `-v` and/or `--version` option to print the code version and if possible the compilation flags

**Comment by jryates** [comment]
I've got a prototype for this, I just want to check one thing. At the moment if you run wannier90 with no arguments it tries to read wannier.win. I think that was a mistake - and it would be better if the wannier90 printed usage information and quit. Do you agree?

**Comment by mostofi** [comment]
@jryates - I agree.

**Comment by giovannipizzi** [comment]
I agree as well!
