### ISSUE TITLE
How to modify the source program to output a  wannier90_hr.dat file with longer number of significant figures

### ISSUE THREAD

**Issue by guobd-huagong** [wannier-developers/wannier90#386]
Hi, 

In the wannier90 program, the default output of the wannier90_hr.dat file is accurate to 6 digits after the decimal point, and I need to output a file with 14 digits after the decimal point. Before I compile the wannier90 program, what part of the program can be modified to make it output a  wannier90_hr.dat file with longer number of significant figures? 

Thank you!

**Comment by qiaojunfeng** [comment]
`seedname_tb.dat` has more digits, you can try the input tag `write_tb = .true.`

**Comment by jaemolihm** [comment]
The relevant line for `_hr.dat` file is the following. You may change `2F12.6` to `2F20.14`.
https://github.com/wannier-developers/wannier90/blob/2b9973c12e85397fa9564370f6cced16f8428834/src/hamiltonian.F90#L477-L478
