### ISSUE TITLE
About the `PWscf` interface to Wannier90.

### ISSUE THREAD

**Issue by hongyi-zhao** [wannier-developers/wannier90#387]
[Here](http://www.wannier.org/download/) says the following:
```
 Quantum ESPRESSO (PWscf) – stable versions of the interface to Wannier90
 are available in the ‘pwscf’ directory of the distribution
```
However, I checked [the gitlab repository](https://gitlab.com/QEF/q-e.git) and [the latest release](https://github.com/QEF/q-e/releases/download/qe-6.8/qe-6.8-ReleasePack.tgz) of `Quantum ESPRESSO`, and I still couldn't find the `pwscf` directory. Any hints for this question will be highly appreciated.
 
Regards,
HZ

**Comment by jryates** [comment]
to be clear, we should update this text to read
  "are available in the ‘pwscf’ directory of the Wannier90 distribution"
I think that will answer your question.

**Comment by hongyi-zhao** [comment]
Thank you for clearing up the ambiguity. According to the following description in the [README](https://github.com/wannier-developers/wannier90/blob/develop/pwscf/README#L15-L26):
```
====
v6.x
====
Please replace the file to the exact version specified in the folder
name.

Later versions already include the changes as we try to contribute these
immediately to the Quantum ESPRESSO repository.

For instance, the file in folder v6.4 should be used to replace the file
in version 6.4 of Quantum ESPRESSO, but the changes are already included
in v6.5 and following.
```
It seems that users no longer need these files: They have already been included in the latest Quantum ESPRESSO release. Am I right?

**Comment by jryates** [comment]
Yes, that is correct.
