### ISSUE TITLE
Symmetrization of Hamiltonian and atomic orbitalized Wannier function.

### ISSUE THREAD

**Issue by hongyi-zhao** [wannier-developers/wannier90#390]
I've noticed there are two similar tools available currently, which aim to implement the symmetrization of the Hamiltonian and atomic orbital Wannier functions based on the results of wannier90: [wannhr_symm](https://github.com/quanshengwu/wannier_tools/tree/master/utility/wannhr_symm) and [WannSymm](https://github.com/ccao/WannSymm). So, I wonder if Wannier90 itself still doesn’t provide this functionality. See [here](https://github.com/ccao/WannSymm/issues/5) for the related discussion.

Regards,
HZ

**Comment by mostofi** [comment]
Thanks for this suggestion/question. Given that the codes linked above already do this, we (the Wannier Developers Group) do not currently plan to replicate this functionality within Wannier90 in the near term.
