### ISSUE TITLE
wann_main: problem computing schur form 1

### ISSUE THREAD

**Issue by k2jasleen** [wannier-developers/wannier90#391]
Hello,

I am facing a problem in running the Anomalous Hall Conductivity calculation for the surface system. I am not exactly sure why this problem would arise. Is it something to do with the 'wannier90.eig' file? I have read the k-mesh can also be an issue, however, I receive the same error even on increasing the k-mesh density. 

I get an error on running "wannier90.x wannier90.win". The complete error is:
wann_main: problem computing schur form 1
Error on node 0: examine the output/error files for details
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

The input files are:

Would be really grateful for any help.
[wannier90.win.zip](https://github.com/wannier-developers/wannier90/files/7917749/wannier90.win.zip)
[wannier90.eig.zip](https://github.com/wannier-developers/wannier90/files/7917750/wannier90.eig.zip)

Thanks

Best

**Comment by coz1paj** [comment]
[wannier90.win.zip](https://github.com/wannier-developers/wannier90/files/7917745/wannier90.win.zip)

**Comment by coz1paj** [comment]
[wannier90.eig.zip](https://github.com/wannier-developers/wannier90/files/7917746/wannier90.eig.zip)

**Comment by stepan-tsirkin** [comment]
@coz1paj  ,  you are not specifying any projections (and so I guess you do not have any `wannier90.amn` file created). So, you are wannierizing all  calculated bands starting random projections. In my experience, such approach, even if it converges, rarely produces good results.

**Comment by k2jasleen** [comment]
> @coz1paj , you are not specifying any projections (and so I guess you do not have any `wannier90.amn` file created). So, you are wannierizing all calculated bands starting random projections. In my experience, such approach, even if it converges, rarely produces good results.

Thank you so much for your quick response. Yes, the error went away! 
I am just getting very off values for AHC. I believe I need to optimize the parameters in order to get closer values.

Thank you once again!
