### ISSUE TITLE
Ununtu repositories

### ISSUE THREAD

**Issue by stepan-tsirkin** [wannier-developers/wannier90#392]
Hi,
I just recently found that wannier 90 can be installed on ubuntu just via `sudo apt-get install wannier90` That is really nice! 

However, I noticed that while the 3.1 release is available for the [Ubuntu 21.04 (hirsute)](https://packages.ubuntu.com/search?suite=hirsute&searchon=names&keywords=wannier90), only the 3.0 version is available for
[20.04 LTS (focal)](https://packages.ubuntu.com/search?keywords=wannier90&searchon=names&suite=focal&section=all)

I just wonder, how it works and if it is possible to make the newer version of Wannier90 available for older LTS release of Ubuntu ?

**Comment by mostofi** [comment]
It looks like this nice feature is maintained by [Andrius Merkys](https://github.com/merkys). I suggest contacting him.
