### ISSUE TITLE
Wannier90 to calculate AHC along different directions 

### ISSUE THREAD

**Issue by k2jasleen** [wannier-developers/wannier90#395]
Hello,

I am trying to understand and study the AHC along different directions in a cubic Weyl semimetal. One way I have tried to do this is by making slab structures along those directions and then calculating the AHC. However, I am not sure if this is the right way to go about it.
There were two questions that I had:
1. Can WANNIER90 calculate AHC for slab structures? 
2. How can I measure the AHC along different directions in a bulk structure?
Looking forward to some insight. 

Thank you

**Comment by mostofi** [comment]
Please may I suggest you post your question on the Wannier mailing list / forum.
