### ISSUE TITLE
Several examples have an errant `kpoints` block

### ISSUE THREAD

**Issue by jimustafa** [wannier-developers/wannier90#398]
There are several of the `wannier90` examples that have WIN files with an errant `kpoints` block; each line in the block has 4 numbers, instead of 3, as specified in the user guide. It appears that the `kpoints` were generated with the weights as the 4th column. While this is inconsequential, as `wannier90` appears to only read the first 3 numbers in each line, it probably should be fixed so that the examples are consistent with the user guide. If you all agree, I will submit a PR.

**Comment by jryates** [comment]
Well spotted. Yes, that would be good. Thanks!

**Comment by jryates** [comment]
fixed by #401
