### ISSUE TITLE
Purge code base of trailing semicolons

### ISSUE THREAD

**Issue by jimustafa** [wannier-developers/wannier90#400]
As trailing semicolons are unnecessary, it may be best to purge them from the code base. They also seem to cause problems with `fprettify` (see pseewald/fprettify#96). There has been a feature request (pseewald/fprettify#120) to allow for removing trailing semicolons, but it appears that the `fprettify` project may not be maintained anymore.

Going further, I would suggest multiple statements on a line should also be avoided.

**Comment by jryates** [comment]
Thanks for noting this. I'm not sure how the trailing semicolons crept in - presumably from deleting a variable from a multi-line declaration. We only have a few multiline statements, and I'd support removing them.
