### ISSUE TITLE
There are so many failed benchmark tests in the develop branch: `ERROR: only 41 out of 70 tests passed`.

### ISSUE THREAD

**Issue by hongyi-zhao** [wannier-developers/wannier90#405]
On Ubuntu 20.04.3 LTS, I try to compile and test wannier90 develop branch. For more information about the steps, see the following:

```
$ git clone https://github.com/wannier-developers/wannier90.git wannier90.git 
$ cd wannier90.git 
$ module load compiler mkl mpi/2021.4.0
$ module list 

Currently Loaded Modules:
  1) lmod   2) tbb/2021.5.1   3) compiler-rt/2022.0.2   4) oclfpga/2022.0.2   5) compiler/2022.0.2   6) mkl/2022.0.2   7) mpi/2021.4.0

$ git branch 
* develop
  master

$ git log -1
commit 54e57f5a293690cdb66c6257699319c53149f5a3 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: a631853c ac182769
Author: Jonathan Yates <jonathan.yates@materials.ox.ac.uk>
Date:   Sun Feb 27 20:36:05 2022 +0000

    Merge pull request #388 from jimustafa/gitattributes
    
    update gitattributes for github-linguist

$ ncore=$(sudo dmidecode -t 4 | grep 'Core Enabled:' | awk '{a+=$NF}END{print a}')
$ cp config/make.inc.ifort make.inc
$ make all -j $ncore 
$ make doc

#https://www.vasp.at/forum/viewtopic.php?f=4&t=18417#p21569
#https://www.vasp.at/wiki/index.php/Makefile.include#Wannier90_.28optional.29
$ sed -E -i -e 's/^(COMMS=mpi)$/#\1/' make.inc
$ make lib -j $ncore

# Need a python environment to run the tests:
$ eval "$(pyenv init -)"
$ pyenv shell socks5-haproxy
$ make test-parallel
```

The errors are shown below:
```
Test id: 08032022.
Benchmark: default.

tests/testpostw90_boltzwann - silicon.win: Passed.

tests/testpostw90_example04_dos - copper.win: Passed.

tests/testpostw90_example04_pdos - copper.win: Passed.

tests/testpostw90_fe_ahc - Fe.win: **FAILED**.
Different sets of data extracted from benchmark and test.
    More data in test than in benchmark: completeness_x, completeness_y, completeness_z, completeness_weight, ahc_y, ahc_z, ahc_x.

tests/testpostw90_fe_ahc_adaptandfermi - Fe.win: Passed.

tests/testpostw90_fe_dos_spin - Fe.win: Passed.

tests/testpostw90_fe_kpathcurv - Fe.win: Passed.

tests/testpostw90_fe_kpathmorbcurv - Fe.win: Passed.

tests/testpostw90_fe_kpathmorbcurv_ws - Fe.win: Passed.

tests/testpostw90_fe_kslicecurv - Fe.win: Passed.

tests/testpostw90_fe_kslicemorb - Fe.win: Passed.

tests/testpostw90_fe_kubo_Axy - Fe.win: Passed.

tests/testpostw90_fe_kubo_Szz - Fe.win: Passed.

tests/testpostw90_fe_kubo_jdos - Fe.win: Passed.

tests/testpostw90_fe_morb - Fe.win: **FAILED**.
Different sets of data extracted from benchmark and test.
    More data in test than in benchmark: completeness_x, completeness_y, completeness_z, morb_y, morb_z, morb_x, completeness_weight.

tests/testpostw90_fe_morbandahc - Fe.win: **FAILED**.
Different sets of data extracted from benchmark and test.
    More data in test than in benchmark: completeness_x, morb_y, completeness_weight, ahc_x, completeness_y, completeness_z, morb_z, morb_x, ahc_y, ahc_z.

tests/testpostw90_fe_spin - Fe.win: **FAILED**.
Different sets of data extracted from benchmark and test.
    More data in test than in benchmark: completeness_x, spin_z, spin_a, completeness_weight, completeness_y, spin_p, completeness_z, spin_x, spin_y.

tests/testpostw90_gaas_kdotp - gaas.win: Passed.

tests/testpostw90_gaas_sc_eta_corr - gaas.win: Passed.

tests/testpostw90_gaas_sc_xyz - gaas.win: Passed.

tests/testpostw90_gaas_sc_xyz_scphase2 - gaas.win: Passed.

tests/testpostw90_gaas_sc_xyz_scphase2_ws - gaas.win: Passed.

tests/testpostw90_gaas_sc_xyz_ws - gaas.win: Passed.

tests/testpostw90_gaas_shc - GaAs.win: Passed.

tests/testpostw90_pt_kpathbandsshc - Pt.win: Passed.

tests/testpostw90_pt_kpathshc - Pt.win: Passed.

tests/testpostw90_pt_ksliceshc - Pt.win: Passed.

tests/testpostw90_pt_shc - Pt.win: Passed.

tests/testpostw90_pt_shc_ryoo - Pt.win: Passed.

tests/testpostw90_si_geninterp - silicon.win: Passed.

tests/testpostw90_si_geninterp_wsdistance - silicon.win: Passed.

tests/testpostw90_te_gyrotropic - Te.win: Passed.

tests/testpostw90_te_gyrotropic_C - Te.win: Passed.

tests/testpostw90_te_gyrotropic_D0 - Te.win: Passed.

tests/testpostw90_te_gyrotropic_Dw - Te.win: Passed.

tests/testpostw90_te_gyrotropic_K - Te.win: Passed.

tests/testpostw90_te_gyrotropic_NOA - Te.win: Passed.

tests/testpostw90_te_gyrotropic_dos - Te.win: Passed.

tests/testw90_basic1 - wannier.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_basic2 - wannier.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_benzene_gamma_val - benzene.win: Passed.

tests/testw90_benzene_gamma_val_hexcell - benzene.win: Passed.

tests/testw90_benzene_gamma_valcond - benzene.win: Passed.

tests/testw90_bvec - lead.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_cube_format - gaas.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_disentanglement_sawfs - H3S.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example01 - gaas.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example02 - lead.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example02_restart - lead.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example03 - silicon.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example03_labelinfo - silicon.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example03_optmem - silicon.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example04 - copper.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example05 - diamond.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example07 - silane.win: Passed.

tests/testw90_example11_1 - silicon.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example11_2 - silicon.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example21_As_sp - GaAs.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_example26 - gaas.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_gaas_disentanglement_issue192 - gaas.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_lavo3_dissphere - LaVO3.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_na_chain_gamma - Na_chain.win: Passed.

tests/testw90_nnkpt1 - wannier.win (arg(s): -pp): **FAILED**.
Error running job.  Return code: 28

tests/testw90_nnkpt2 - wannier.win (arg(s): -pp): **FAILED**.
Error running job.  Return code: 28

tests/testw90_nnkpt3 - wannier.win (arg(s): -pp): **FAILED**.
Error running job.  Return code: 28

tests/testw90_nnkpt4 - wannier.win (arg(s): -pp): Passed.

tests/testw90_nnkpt5 - wannier.win: Passed.

tests/testw90_precond_1 - gaas1.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_precond_2 - gaas2.win: **FAILED**.
Error running job.  Return code: 28

tests/testw90_write_u_matrices - gaas.win: **FAILED**.
Error running job.  Return code: 28

All done. ERROR: only 41 out of 70 tests passed.
Failed tests in:
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testpostw90_fe_ahc/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testpostw90_fe_morb/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testpostw90_fe_morbandahc/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testpostw90_fe_spin/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_basic1/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_basic2/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_bvec
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_cube_format
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_disentanglement_sawfs
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example01
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example02
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example02_restart
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example03
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example03_labelinfo
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example03_optmem
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example04
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example05
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example11_1/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example11_2/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example21_As_sp
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_example26
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_gaas_disentanglement_issue192
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_lavo3_dissphere/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_nnkpt1/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_nnkpt2/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_nnkpt3/
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_precond_1
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_precond_2
	/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/test-suite/tests/testw90_write_u_matrices
make: *** [Makefile:181: test-parallel] Error 1
(cd ./src/obj && make -f ../Makefile.2 wannier)
make[1]: Entering directory '/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/src/obj'
make[1]: Nothing to be done for 'wannier'.
make[1]: Leaving directory '/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/src/obj'
(cd ./src/obj && make -f ../Makefile.2 post)
make[1]: Entering directory '/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/src/obj'
make[1]: Nothing to be done for 'post'.
make[1]: Leaving directory '/home/werner/Public/repo/github.com/wannier-developers/wannier90.git/src/obj'
```
Any hints for fixing these problems?

Regards,
HZ

**Comment by jimustafa** [comment]
Responding to an email from @hongyi-zhao:

> Dear Jamal Mustafa,
> 
> I noticed that you did some commits to wannier90 repository recently, and
> based on tries, currently, there are so many failed benchmark tests in
> the develop branch [1].
> 
> I'm not sure if there is a correlation between the above events.

Regarding the test suite, the recent changes I have made should have been inconsequential. No changes were made to the tests, and the changes to the actual source code was relatively minor, only a small pruning of an unused input parameter. Anyways, those changes did pass the test suite run through GitHub Actions (see https://github.com/wannier-developers/wannier90/actions). Furthermore, running the test suite on my local computer did not indicate there were any issues. Are you running the tests in parallel (`make test-parallel`) or serial (`make test-serial`)?

**Comment by hongyi-zhao** [comment]
> On Thu, Mar 10, 2022 at 2:22 PM Jamal Mustafa ***@***.***>
> wrote:

> Responding to an email from @hongyi-zhao <https://github.com/hongyi-zhao>:
>
> Dear Jamal Mustafa,
>
> I noticed that you did some commits to wannier90 repository recently, and
> based on tries, currently, there are so many failed benchmark tests in
> the develop branch [1].
>
> I'm not sure if there is a correlation between the above events.
>
> Regarding the test suite, the recent changes I have made should have been
> inconsequential. No changes were made to the tests, and the changes to the
> actual source code was relatively minor, only a small pruning of an unused
> input parameter. Anyways, those changes did pass the test suite run through
> GitHub Actions (see
> https://github.com/wannier-developers/wannier90/actions). Furthermore,
> running the test suite on my local computer did not indicate there were any
> issues. Are you running the tests in parallel (make test-parallel) or
> serial (make test-serial)?
>

 I run the tests in parallel as follows, which I've mentioned at the beginning of this issue
filed by me:

$ make test-parallel

Regards,
HZ

**Comment by JeromeCCP9** [comment]
Dear Hongyi Zhao,

I think you have built the code in several steps, partially with DMPI set and partially without.  I believe that this might cause your problem.

Please, could you try an experiment for me?  Could you setup the MPI enabled make.inc  file (i.e. without your sed commnd) and then "make clean" and then issue "make all; make test-parallel" ?  Please, could you tell me the whether this corrects the problem?

Also, please avoid using parallel make at the moment because I think it can cause problems (i.e. please do not use the "-j" flag to make).  I have written a new makefile which does work in parallel, but it is not yet contributed to the main repo (hopefully very soon).

Yours,
Jerome.

**Comment by hongyi-zhao** [comment]
@JeromeCCP9 You're absolutely right. The following steps work smoothly:

```shell
$ git clone https://github.com/wannier-developers/wannier90.git wannier90.git 
$ cd wannier90.git 
$ module load compiler mkl mpi/2021.4.0

$ ncore=$(sudo dmidecode -t 4 | grep 'Core Enabled:' | awk '{a+=$NF}END{print a}')
$ cp config/make.inc.ifort make.inc
$ make all -j $ncore 
$ make doc

# Need a python environment to run the tests:
$ eval "$(pyenv init -)"
$ pyenv shell socks5-haproxy
$ make test-parallel

#https://www.vasp.at/forum/viewtopic.php?f=4&t=18417#p21569
#https://www.vasp.at/wiki/index.php/Makefile.include#Wannier90_.28optional.29
$ sed -E -i -e 's/^(COMMS=mpi)$/#\1/' make.inc
$ make lib -j $ncore
$ make test-serial
```
Some additional remarks:

1. I compiled with parallel make, all the serial and parallel tests passed successfully.
2. It seems that `make lib` will also recompile `wannier90.x` and `postw90.x`. I feel very confused about this behavior.
3. It's nice to know you've written a new Makefile which does work in parallel.

**Comment by JeromeCCP9** [comment]
Dear Hongyi-Zhao,

the reason for this behaviour is that now wannier90.x and postw90.x are essentially just wrappers which call subroutines contained in (the new version of) the library.  Therefore these executables depend on the (new) library.  The "lib" make target will prepare both the "old" and "new" libraries, and because of the second one, the main binaries must also be regenerated.

The "old" library is serial regardless of whether or not you define MPI in the make.inc, so you don't need to worry about that.

I'm glad parallel make works on your machine; it is not always safe.  In any event, I hope we will adopt the changed make system because it is much faster (since it avoids recursive make, there is a more complete specification of the dependencies).

I hope that this is an ok resolution for you.  Please, if you find other issues, which is perfectly possible because we have made significant changes(!), then post again.  But it should be ok :-)

Yours,
Jerome.

**Comment by hongyi-zhao** [comment]
> the reason for this behaviour is that now wannier90.x and postw90.x are essentially just wrappers which call subroutines contained in (the new version of) the library. Therefore these executables depend on the (new) library. The "lib" make target will prepare both the "old" and "new" libraries, and because of the second one, the main binaries must also be regenerated.
> 
> The "old" library is serial regardless of whether or not you define MPI in the make.inc, so you don't need to worry about that.

Thank you for letting me know these cutting edge ongoing changes in this repository. But as you can see, for my situation, vasp can only call wannier90 library serially as noted [here](https://www.vasp.at/wiki/index.php/Makefile.include#Wannier90_.28optional.29), and I hope to have a parallel version of wannier90 that can be used alone at the same time. This will cause the dilemma that for this purpose, I have to compile parallel and serial versions of wannier90 independently and install them in different locations. In short, the compilation steps shown in https://github.com/wannier-developers/wannier90/issues/405#issuecomment-1064674769 will ultimately build a serial version of wannier90.

Regards,
HZ

**Comment by JeromeCCP9** [comment]
this is interesting.  Yes, I'm afraid that it would be best to have serial and parallel builds in different directories.

Doing both in the same directory is not a good idea because pretty much all the code contains (indirect) references to MPI.  The reason for this is quite subtle and we couldn't find a solution: essentially fortran module files contain more information than a simple header file, and this means that the comms module file, which wraps up the mpi routines, is different depending on whether the real mpi is being used or not (in the serial case).  If it was a simple c-style header instead of a module (with just a list of function interfaces) then there would be no such dependency.  We are a little irritated about it, because it means exactly that all the objects that use the comms module do indeed need to be rebuilt if you change between serial and parallel.  (If it were c code only the comms routines would need to be rebuilt.)

You would need the serial version only for the (old) library.

We will add some comments about this in the build instructions.
Yours,
Jerome.

**Comment by hongyi-zhao** [comment]
> You would need the serial version only for the (old) library.

Do you mean that compiling and using the serial version of Wannier90 is only necessary when using it as a third-party interface library (for other programs that have not yet implemented support for its parallel version, such as VASP), and that otherwise the parallel version is always recommended?

**Comment by JeromeCCP9** [comment]
yes, exactly :-)

edit: we are still designing the parallel library, but we hope that when it is finished (the next main release) most codes that used the old library will move to using the new version.
