### ISSUE TITLE
param_read_chk: Mismatch in nntot

### ISSUE THREAD

**Issue by hetian-chen** [wannier-developers/wannier90#410]
This problem occurred when I calculated the band with "restart = plot", while there was no problem if I directly calculated the band. I am pretty sure that the .chk file was just generated by wannier90.x. Can anyone tell me what's wrong?

**Comment by hetian-chen** [comment]
This is what I got from  w90chk2chk:
-------------------------------------------------------------------
Number of bands: 50
Excluded bands: 1,2,3,4,5,6.
Real lattice: read.
Reciprocal lattice: read.
Num kpts:729
mp_grid: read.
kpt_latt: read.
nntot:1906824895

**Comment by jryates** [comment]
Your second message shows us that nntot has an unphysical value. I have never seen this happen before so either: there is an issue with your compilation of wannier90 or you are doing something unusual.
But that is all I can say. In order for us to investigate can you:

1. See if you can reproduce this error in a smaller test case
2. Either post those input files, or the original ones
3. Tell us which version of wannier90, and which compiler / libraries you are using.

**Comment by hetian-chen** [comment]
> Your second message shows us that nntot has an unphysical value. I have never seen this happen before so either: there is an issue with your compilation of wannier90 or you are doing something unusual. But that is all I can say. In order for us to investigate can you:
> 
> 1. See if you can reproduce this error in a smaller test case
> 2. Either post those input files, or the original ones
> 3. Tell us which version of wannier90, and which compiler / libraries you are using.

Thank you very much! The .chk file can be read correctly on another computer. I never met this problem on this computer before. Maybe something has been changed by others.  Wannier90-3.1.0 is used and intel compilers and libraries 2016.3.210 are used. I try recompiling wannier90 but it makes no difference.

**Comment by jryates** [comment]
We don't have enough info to reproduce - and I suspect this is a local compilation issue.
