### ISSUE TITLE
Hamiltonian matrix element in k-space

### ISSUE THREAD

**Issue by Simba2805** [wannier-developers/wannier90#422]
Dear Developers,

May I know, that wannier90 provides the Hamiltonian matrix elements in real space only or it also provides them in k space?
As far as I know, the wannier90 writes the Hamiltonian in the `hr.dat` file.

My questions are:
(1) If it does not provide in k-space, what is the method to get it? Where do I get the lattice vectors (R) and k-vectors to do a Fourier transform? The first three columns in the `hr.dat` file are the lattice vectors? The first few lines of the `hr.dat` file are

written on 22May2022 at 16:44:06 
           8
         231
    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1
....
    1    1    1    1    1    1
   -9   -5    0    1    1    0.001065    0.000003
   -9   -5    0    2    1   -0.001595   -0.001326
   -9   -5    0    3    1   -0.000971   -0.001890
   -9   -5    0    4    1   -0.000957   -0.000914
....

The last two columns are the real and imaginary parts of the matrix elements in the Hamiltonian. What are the first three columns?
is it `R`?
I will also need `k vectors`, for the Fourier transform, where do I get them?

(2) My projected bands from the Wannier90 calculations are well fitted with the DFT bands, still, I have a sizeable `imaginary` part in the matrix elements. Is it wrong that the imaginary parts of the matrix elements are not zero?

**Comment by mostofi** [comment]
Please may I suggest that you post your question on the Wannier mailing list / forum.
