### ISSUE TITLE
wannier90 to calculate Lindhard response function

### ISSUE THREAD

**Issue by aali28** [wannier-developers/wannier90#451]
Dear all, 

Following the reference (https://link.springer.com/article/10.1007/s10948-018-4790-9#Sec2)

How to calculate the Lindhard response function after interpolation?
For example, as done in many papers, https://link.springer.com/article/10.1007/s10948-018-4790-9#Sec2 and https://iopscience.iop.org/article/10.1088/1361-648X/ab8522 etc.

Is it possible with wannier90 after the interpolation?

I would be grateful for your help.

**Comment by mostofi** [comment]
Hi there. Should be possible, but there's currently no function in Wannier90 to do it. I suggest you ask on the mailing list forum in case someone in the community has a private implementation that they might be willing to share with you.
