### ISSUE TITLE
Support for multiple version of the documentation

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#475]
Maybe using [mike](https://github.com/jimporter/mike)?

Anyway we want to support from 4.0 onwards (we could think to have a 4.0alpha if we want to check how it works right now, with 2 versions)

**Comment by giovannipizzi** [comment]
Actually it would be good to implement it soon, as the URLs might change once this is done

**Comment by qiaojunfeng** [comment]
Done in #493
