### ISSUE TITLE
Fix `make docs`

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#480]
With the switch to markdown documentation, `make docs` does not work anymore.

One could run now `mkdocs build`, but one typically needs to install some requirements.
Therefore, better to just keep `make docs` and have it print the 2-3 lines of what you have to do to compile the docs.

**Comment by mikibonacci** [comment]
Also the `make clean` and `make veryclean` should change accordingly (probably we just need to delete the `site` folder in the docs)
