### ISSUE TITLE
problem with xsf writing in parallel

### ISSUE THREAD

**Issue by pleoluxbg** [wannier-developers/wannier90#495]
XSF files are incorrectly scaled by number of processors when wannier90.x (develop branch) run in parallel (although u matrices are identical).

**Comment by JeromeCCP9** [comment]
Looks like an incorrect MPI reduction of the RS Wannier functions.  I'll check it out.

**Comment by JeromeCCP9** [comment]
I pushed a change to c-for-gc that should fix this issue.  Please can you test commit c7eb18ac and confirm this is resolved?
J.

**Comment by pleoluxbg** [comment]
that's great. Thank you very much
