### ISSUE TITLE
Error in postw90.x when calculate complex optical conductivity

### ISSUE THREAD

**Issue by suhang20001115** [wannier-developers/wannier90#497]
Dear all,
When I use fixed smear to calculate complex optical conductivity by [kubo_adpt_smr=false] and [kubo_smr_fixed_en_width=0.1] The imaginary part of the optical conductivity diagonal element is obtained normally, but the real part shows NaN ; the real part of the non-diagonal element is obtained normally, but the imaginary part shows NaN. How can I solve it?
Here are my input file and two of the output files
[wannier90.win]
berry = ture
berry_task = kubo
kubo_freq_max = 6
berry_kmesh = 301 301 1
kubo_adpt_smr = false
kubo_smr_fixed_en_width = 0.1
......
[wannier90-kubo_S_xx.dat]
0.00000000E+00             NaN -0.47332911E-14
0.10000000E-01             NaN -0.59389050E+01
0.20000000E-01             NaN -0.11879968E+02
0.30000000E-01             NaN -0.17825352E+02
......
[wannier90-kubo_S_xy.dat]
0.00000000E+00 -0.41968789E-01             NaN
0.10000000E-01 -0.41877977E-01             NaN
0.20000000E-01 -0.41605482E-01             NaN
0.30000000E-01 -0.41151120E-01             NaN
0.40000000E-01 -0.40514583E-01             NaN
......

**Comment by JeromeCCP9** [comment]
Hi suhang20001115!

I cannot reproduce this problem, either with version 3.1.0 nor with the current development branches: when I use 

```
kubo_adpt_smr = false
kubo_smr_fixed_en_width = 0.1
```

the outputs you mention all appear well formed.

Please, could you send a case that demonstrates the problem?  Perhaps you could adapt one of the test cases to show the error, then I can attempt to reproduce it?  Or else, please could you provide a fuller description of the problem/full inputs?

With many thanks, 
yours,
Jerome Jackson

**Comment by suhang20001115** [comment]
@JeromeCCP9 
I've solved this problem in version 3.1.0,  2.0 have this problem。Thanks!

**Comment by JeromeCCP9** [comment]
Ok!  So, this was fixed already in v3.1.0, great!
