### ISSUE TITLE
\gamma_{yzz} appears twice

### ISSUE THREAD

**Issue by pinegym** [wannier-developers/wannier90#522]
Dear Developers

On page 136 of the user guide, \gamma_{yzz} appears twice, as it also does on line 996 of gyrotropic.F90. Could it be that the second occurrence of "yzz" is meant to be "xyx"? Please let me know if this interpretation is correct.

Best regards

**Comment by stepan-tsirkin** [comment]
You are right, this is a typo.

In the corresponding column the variable `y` is written, which is equal to `arr33N(3, 1, :) `  . The `3` here is `z`which by Levi-Chevita is converted to `xy`, so the component is called `xyx` 

https://github.com/wannier-developers/wannier90/blob/8059cc53fdc739d7c0f5a8e03d59094f6fe709d2/src/postw90/gyrotropic.F90#L1230-L1238

You are right, you are welcome to make a small PR to fix that.

**Comment by pinegym** [comment]
Thank you very much for your prompt response. I have submitted a PR to fix that.
