### ISSUE TITLE
write_dmb in pw2wannier90

### ISSUE THREAD

**Issue by greschd** [wannier-developers/wannier90#62]
@yusukenomura , do you have a version of pw2wannier90 that writes the ``.dmb`` file?

I had the idea of using the D matrix to calculate symmetry protected topological invariants (e.g. mirror chern numbers) -- so I would like to try this. Since I need to be able to compute it on a non-symmetric k-mesh, I might have to add a flag to compute only the D matrix, without the indices specifying how the k-mesh transforms.

**Comment by yusukenomura** [comment]
Sorry for late reply. 
We are currently working on updating pw2wannier90.f90 for v.6.0. 

Attached please find the old version which works on v.5.4.0. 
What you can do is to copy the attached pw2wannier90.f90 to PP/src/ in Quantum Espresso v.5.4.0, 
and then recomplie pw2wannier90.x . 

pw2wannier90.f90 which is compatible with v.6.0 will hopefully be available soon. 

Yusuke

[pw2wannier90.f90.zip](https://github.com/wannier-developers/wannier90/files/481543/pw2wannier90.f90.zip)

**Comment by greschd** [comment]
Thanks for the file. Given that the release 6.0 will be pretty soon I think I'll probably work directly on that version.
