### ISSUE TITLE
test_si_geninterp in parallel with intel 13

### ISSUE THREAD

**Issue by sponce24** [wannier-developers/wannier90#64]
Dear all, 

The full buildbot test-farm should now be passing except "WAN-farmer_intel13". 
http://129.67.86.21:8010/builders/WAN-farmer_intel13/builds/21/steps/test_wannier/logs/stdio

I looked into it but could not solve it. 

The bot uses intel 13.1.3 with openmpi 1.8.8.

The make.inc used can be found in wannier90/test-suite/config/EPW_testfarm/farmer_intel13.inc

When run in parallel with 4 mpi I do not get any error but the silicon_geninterp.dat contain mostly 0 ...

```
# Written on 19Sep2016 at 18:59:49 
# Input file comment: Sample points for testing implementation
#  Kpt_idx  K_x (1/ang)       K_y (1/ang)        K_z (1/ang)       Energy (eV)      EnergyDer_x       EnergyDer_y       EnergyDer_z
         1  0.2328140398      0.2328140398      0.2328140398       0.000000000       0.000000000       0.000000000       0.000000000
         1  0.2328140398      0.2328140398      0.2328140398       0.000000000       0.000000000       0.000000000       0.000000000
         1  0.2328140398      0.2328140398      0.2328140398       0.000000000       0.000000000       0.000000000       0.000000000
         1  0.2328140398      0.2328140398      0.2328140398       0.000000000       0.000000000       0.000000000       0.000000000
         1  0.2328140398      0.2328140398      0.2328140398       0.000000000       0.000000000       0.000000000       0.000000000
         1  0.2328140398      0.2328140398      0.2328140398       0.000000000       0.000000000       0.000000000       0.000000000
         1  0.2328140398      0.2328140398      0.2328140398       0.000000000       0.000000000       0.000000000       0.000000000
         1  0.2328140398      0.2328140398      0.2328140398       0.000000000       0.000000000       0.000000000       0.000000000
         2 -0.1746105299      0.1746105299      0.1746105299       0.000000000       0.000000000       0.000000000       0.000000000
         2 -0.1746105299      0.1746105299      0.1746105299       0.000000000       0.000000000       0.000000000       0.000000000
         2 -0.1746105299      0.1746105299      0.1746105299       0.000000000       0.000000000       0.000000000       0.000000000
         2 -0.1746105299      0.1746105299      0.1746105299       0.000000000       0.000000000       0.000000000       0.000000000
         2 -0.1746105299      0.1746105299      0.1746105299       0.000000000       0.000000000       0.000000000       0.000000000
         2 -0.1746105299      0.1746105299      0.1746105299       0.000000000       0.000000000       0.000000000       0.000000000
         2 -0.1746105299      0.1746105299      0.1746105299       0.000000000       0.000000000       0.000000000       0.000000000
         2 -0.1746105299      0.1746105299      0.1746105299       0.000000000       0.000000000       0.000000000       0.000000000
         3   0.000000000       2.048763551       0.000000000       0.000000000       0.000000000       0.000000000       0.000000000
         3   0.000000000       2.048763551       0.000000000       0.000000000       0.000000000       0.000000000       0.000000000
         3   0.000000000       2.048763551       0.000000000       0.000000000       0.000000000       0.000000000       0.000000000
         3   0.000000000       2.048763551       0.000000000       0.000000000       0.000000000       0.000000000       0.000000000
         3   0.000000000       2.048763551       0.000000000       0.000000000       0.000000000       0.000000000       0.000000000
         3   0.000000000       2.048763551       0.000000000       0.000000000       0.000000000       0.000000000       0.000000000
         3   0.000000000       2.048763551       0.000000000       0.000000000       0.000000000       0.000000000       0.000000000
         3   0.000000000       2.048763551       0.000000000       0.000000000       0.000000000       0.000000000       0.000000000
```

PS: It seems I cannot add "labels" .

**Comment by giovannipizzi** [comment]
Can it be a problem with `-O3` instead of `-O2`? The tests with intel13 and 15 both work on farmer1, and farm2_intel13.inc also work (and has `-O2`, even if there are other library changes).

Also, is it correct to use `mpif90` to test the intel compiler in farmer_intel13? I thought it was pointing by default to `gfortran` rather than `ifort`. Is there a way to check which compiler is actually used?

**Comment by sponce24** [comment]
intel 15 on farmer 1 pass (but this is serial with ifort only)
intel 13 on farmer 2 pass also  (but this is serial with ifort only)

intel 13 on farmer 1 does not pass (in parallel with ifort and openmpi, i.e. with ifort and mpif90). 
This means /obj are compiled with ifort and /objp are compiled with mpif90 -DMPI -O3 -assume byterecl -g -traceback

So I did the test and you are correct. The problem is -03
FCOPTS=-O3 -assume byterecl -g -traceback -I/home/farmer/local/openmpi188_intel13/include/
LDOPTS=-O3

==> does not work

and with 
FCOPTS=-O2 -assume byterecl -g -traceback -I/home/farmer/local/openmpi188_intel13/include/
LDOPTS=-O2

works perfectly. 

So you can either modify the 
test-suite/config/EPW_testfarm/farmer_intel13.inc 
and put -O2 but then it needs to be clear somewhere that Wannier does not support -O3.

In any case, I would consider that a bug if Wannier does not work with -O3. Maybe its worth investigating?

Best, 

Samuel

**Comment by giovannipizzi** [comment]
Thanks a lot for testing! 

Indeed, it's not good it's not working. 
I would tend to keep the test there, and try to figure out why it's not working. 
Maybe if we don't solve it before the release we can just mention this in the use guide,  but it's better to figure out where the problem is. 
I'll try to give a look to this ASAP.

**Comment by jryates** [comment]
On 21 Sep 2016, at 20:35, Giovanni Pizzi <notifications@github.com> wrote:

> Thanks a lot for testing!
> 
> Indeed, it's not good it's not working. 
> I would tend to keep the test there, and try to figure out why it's not working. 
> Maybe if we don't solve it before the release we can just mention this in the use guide, but it's better to figure out where the problem is. 
> I'll try to give a look to this ASAP.

This sounds very much like an bug in ifort rather than wannier90.
I checked and I can reproduce this in serial with ifort 13.1.3 , however with 14.0.2 it works correctly.

Jonathan

**Comment by sponce24** [comment]
Its confirmed. 
I tried with intel 15.0.3 20150407 in parallel with openmpi and with -O3 and it works.
I've made a pull request #68  about it. 

Best, 

Samuel
